# pyright: reportUnusedExpression=false
# ruff: noqa: B018

"""🏆 FIFA World Cup 2026 Prediction & Simulation Dashboard.

This module orchestrates a reactive front-end dashboard built natively in Marimo,
designed to ingest, evaluate, and visualize predictive outputs generated by the
underlying multi-model ensemble pipeline.

Execution Vectors:
    $ uv run marimo edit dashboard.py
    $ uv run marimo run dashboard.py

Dashboard Layout Matrix:
    1. 🚀 PARAMETER METRIC BANNER
       Displays real-time execution states, active pipeline configurations,
       and optimal consensus blend weights.

    2. 🎲 STOCHASTIC FRONTIER
       Knockout progression survival probabilities via Plotly.
       Multiverse probability ledger.

    4. 🏟️ DETERMINISTIC HORIZON
       Group Stage tables and matches.
       Knockout Waterfall matches.

    5. 🧪 MICRO HORIZON SANDBOX
       Custom head2head capabilities comparisons.
       ---to implement: head2head sandbox match.---

Design Considerations:
    - This file explicitly silences 'unused-expression' warnings via file-level
      Pyright and Ruff directives to accommodate Marimo's terminal layout pattern.
    - Uses highly scoped responsive container components to guarantee dark-mode
      visual parity and strict monospaced numerical alignment.
"""

import marimo

__generated_with = "0.23.9"
app = marimo.App(width="medium", app_title="fifa-world-cup-2026-predictor")


@app.cell
def _():
    import glob
    import json
    import os

    import marimo as mo
    import numpy as np
    import pandas as pd
    import plotly.graph_objects as go

    # Define styling palette
    DARK_THEME = {
        "background": "#121212",
        "paper": "#1e1e1e",
        "text": "#e0e0e0",
        "accent": "#00adb5",
        "muted": "#6c757d",
    }

    # Apply global custom overrides to Plotly dark layout defaults
    def apply_mission_control_layout(fig):
        fig.update_layout(
            template="plotly_dark",
            paper_bgcolor=DARK_THEME["paper"],
            plot_bgcolor=DARK_THEME["background"],
            font=dict(color=DARK_THEME["text"], family="JetBrains Mono, monospace"),
            title=dict(
                font=dict(
                    family="'Inter', 'Segoe UI', system-ui, sans-serif",
                    size=16,
                    weight="bold",
                )
            ),
            margin=dict(l=40, r=40, t=50, b=40),
        )
        return fig

    # ⚡ GLOBAL CSS INJECTION LAYER
    # Sweeps away default browser serifs and unifies the app layout typography
    # Tailors specific display rules for both large structural matrices and high-density tables
    #
    mo.Html(
        f"""
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');

            /* Force typography rules across all markdown header blocks globally */
            .marimo-output h1, h1 {{
                font-family: 'Inter', 'Segoe UI', system-ui, sans-serif !important;
                font-weight: 800 !important;
                letter-spacing: -1.5px !important;
                color: #ffffff !important;
            }}

            .marimo-output h2, h2 {{
                font-family: 'Inter', 'Segoe UI', system-ui, sans-serif !important;
                font-weight: 700 !important;
                letter-spacing: -1px !important;
                color: #ffffff !important;
                border-bottom: 1px solid #2d2d2d !important;
                padding-bottom: 8px !important;
            }}

            .marimo-output h3, h3, .marimo-output h4, h4 {{
                font-family: 'Inter', 'Segoe UI', system-ui, sans-serif !important;
                font-weight: 600 !important;
                letter-spacing: -0.5px !important;
                color: {DARK_THEME["accent"]} !important;
            }}

            /* Keep pure markdown body text crisp and readable */
            .marimo-output p, p {{
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif !important;
                color: {DARK_THEME["text"]} !important;
                font-size: 14px !important;
                line-height: 1.6 !important;
            }}

            /* LAYER A: STANDARD MARKDOWN TABLES */
            .marimo-output table:not([class*="marimo"]) {{
                width: 100% !important;
                max-width: 900px !important;
                margin: 15px 0 !important;
                border-collapse: collapse !important;
            }}

            .marimo-output table:not([class*="marimo"]) th {{
                padding: 10px 16px !important;  /* Generous breathing room */
                font-size: 13px !important;     /* Highly visible title text */
                font-family: 'Inter', sans-serif !important;
                background-color: #1a1a1a !important;
                color: #ffffff !important;
                text-align: left !important;
                border-bottom: 2px solid #333 !important;
            }}

            .marimo-output table:not([class*="marimo"]) td {{
                padding: 10px 16px !important;  /* Comfortable vertical tracking space */
                font-size: 13px !important;
                font-family: -apple-system, BlinkMacSystemFont, sans-serif !important;
                color: {DARK_THEME["text"]} !important;
                border-bottom: 1px solid #262626 !important;
            }}

            /* Inline code blocks within the configuration table keep their clean monospace style */
            .marimo-output table:not([class*="marimo"]) td code {{
                font-family: 'JetBrains Mono', monospace !important;
                font-size: 12px !important;
                background: #262626 !important;
                padding: 2px 6px !important;
                border-radius: 4px !important;
            }}

            /* LAYER B: HIGH-DENSITY INTERACTIVE DATA TABLES */
            [data-testid="ns-table"], div[class*="table-wrapper"] {{
                width: 100% !important;
            }}

            [data-testid="ns-table"] th, div[class*="table"] table th {{
                padding: 4px 6px !important;   /* Ultra-tight cell sizing to prevent overflow */
                font-size: 11px !important;
                font-family: 'Inter', sans-serif !important;
                font-weight: 700 !important;
                background-color: #151515 !important;
            }}

            [data-testid="ns-table"] td, div[class*="table"] table td {{
                padding: 4px 6px !important;
                font-size: 11px !important;
                font-family: 'JetBrains Mono', monospace !important; /* Perfect vertical alignment for integers/decimals */
                line-height: 1.2 !important;
            }}

            div[class*="table"] div, div[class*="grid"] div {{
                gap: 1px !important;
            }}
        </style>
        """
    )
    return (
        DARK_THEME,
        apply_mission_control_layout,
        glob,
        go,
        json,
        mo,
        np,
        os,
        pd,
    )


@app.cell
def _(glob, json, os, pd):
    # 1. Discover the latest execution run folder dynamically
    run_folders = sorted(glob.glob(os.path.join("data", "runs", "run_*")))
    if not run_folders:
        raise FileNotFoundError(
            "❌ Operational error: No simulation artifacts found in data/runs/."
        )

    latest_run_dir = run_folders[-1]
    run_id = os.path.basename(latest_run_dir)

    # 2. Ingest structured datasets into memory
    df_tournament = pd.read_csv(
        os.path.join(latest_run_dir, "predicted_tournament.csv")
    )
    df_tables = pd.read_csv(os.path.join(latest_run_dir, "final_group_tables.csv"))
    df_capabilities = pd.read_csv(
        os.path.join(latest_run_dir, "pre_tournament_capabilities.csv")
    )

    # Safely check for optional Monte Carlo stochastic arrays
    forecast_path = os.path.join(latest_run_dir, "monte_carlo_forecast.csv")
    has_stochastic = os.path.exists(forecast_path)
    df_forecast = pd.read_csv(forecast_path) if has_stochastic else None

    # 3. Parse system config states from JSON metadata
    with open(os.path.join(latest_run_dir, "metadata.json"), "r") as f:
        metadata = json.load(f)

    config = metadata["config"]
    weights = metadata["ensemble_weights"]
    return (
        config,
        df_capabilities,
        df_forecast,
        df_tables,
        df_tournament,
        has_stochastic,
        run_id,
        weights,
    )


@app.cell
def _(config, mo, run_id, weights):
    # Technical metric banner
    # 1. Resolve clean status strings ahead of time to keep the layout matrix readable
    nudge_status = "🟢 ACTIVE" if config["use_prior_nudge"] else "🔴 DISABLED"
    nudge_val = (
        f"📏 {config['nudge_strength']}" if config["use_prior_nudge"] else "❌ N/A"
    )

    mc_status = (
        f"🎲 {config['monte_carlo_runs']}"
        if config["run_monte_carlo"]
        else "🔴 DISABLED"
    )

    # 2. Render the streamlined technical metric banner
    header_panel = mo.md(
        f"""
        # 🚀 FIFA WORLD CUP 2026 PREDICTOR
        ### 📊 `{run_id}`
        | Parameter | Value | Ensemble Model | Weight |
        | :--- | :--- | :--- | :--- |
        | **Bayesian Prior Nudge** | {nudge_status} | 🧮 **Poisson MLE Baseline** | `{weights["poisson"]:.3f}` |
        | **Nudge Amplitude** | `{nudge_val}` | 📈 **Dynamic ELO Rating** | `{weights["elo"]:.3f}` |
        | **Monte Carlo Engine** | {mc_status} | 🌲 **XGBoost Count Regressor** | `{weights["xgb"]:.3f}` |
        """
    )
    header_panel
    return


@app.cell
def _(DARK_THEME, df_capabilities, df_forecast, has_stochastic, mo):
    # 1. Initialize safe fallbacks to prevent UnboundLocalErrors in alternative execution runs
    stage_selector = None
    team_count_slider = None

    ALL_POSSIBLE_STAGES = {
        "R32 %": ("R32 %", "Round of 32", "#4a47a3"),
        "R16 %": ("R16 %", "Round of 16", "#ff7b54"),
        "QF %": ("QF %", "Quarter-Finals", "#1f4068"),
        "SF %": ("SF %", "Semi-Finals", "#16c79a"),
        "Final %": ("Final %", "Finalist", "#e6739f"),
        "Champion %": ("Champion %", "Champion", "#00adb5"),
    }

    # 2. Evaluate environmental conditions and build layout frames
    if has_stochastic and df_forecast is None:
        stochastic_controls = mo.md("")

    elif has_stochastic and df_forecast is not None:
        available_column_stages = {
            v[1]: k for k, v in ALL_POSSIBLE_STAGES.items() if k in df_forecast.columns
        }

        # Target display label defaults directly
        default_stages = [
            v[1]
            for k, v in ALL_POSSIBLE_STAGES.items()
            if k in ["QF %", "SF %", "Final %", "Champion %"]
            and k in df_forecast.columns
        ]

        # Instantiate active interactive control widgets
        stage_selector = mo.ui.multiselect(
            options=available_column_stages,
            value=default_stages,
            label="🏆 TOURNAMENT PROGRESSION LAYERS",
        )

        team_count_slider = mo.ui.slider(
            start=4, stop=len(df_capabilities), step=1, value=8, label="🏃 SQUAD DEPTH"
        )

        stochastic_controls = mo.md(
            f"""
            ## 🎲 STOCHASTIC FRONTIER
            <div style="display: flex; gap: 30px; margin: 15px 0;">
                <div style="flex: 2; background: {DARK_THEME["paper"]}; padding: 14px; border-radius: 6px; border: 1px solid #333;">{stage_selector}</div>
                <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 14px; border-radius: 6px; border: 1px solid #333;">{team_count_slider}</div>
            </div>
            """
        )
    else:
        stochastic_controls = mo.md("")
    stochastic_controls
    return ALL_POSSIBLE_STAGES, stage_selector, team_count_slider


@app.cell
def _(
    ALL_POSSIBLE_STAGES,
    apply_mission_control_layout,
    df_forecast,
    go,
    has_stochastic,
    mo,
    stage_selector,
    team_count_slider,
):
    if not has_stochastic or df_forecast is None:
        stochastic_visual = mo.md(
            """
            ### 🎲 STOCHASTIC PROBABILITY ANALYSIS
            > 🔴 Monte Carlo suite disabled for active simulation run:
            > switch `RUN_MONTE_CARLO = True` to populate this predictive node.
            """
        )
    else:
        # 1. Read reactive parameters from the control cell
        selected_stage_keys = stage_selector.value
        num_display_teams = team_count_slider.value

        if not selected_stage_keys:
            stochastic_visual = mo.md(
                "> ⚠️ **Visualization Alert:** Please select at least one tournament progression layer to render the chart analysis."
            )
        else:
            # 2. Extract and sort contender profiles dynamically based on baseline Championship power
            top_contenders = (
                df_forecast.sort_values(by="Champion %", ascending=False)
                .head(num_display_teams)
                .copy()
            )

            # 3. Resolve actual CSV column names ahead of time to compute dynamic scaling boundaries
            resolved_csv_cols = []
            for stoch_col_key in selected_stage_keys:
                if stoch_col_key in ALL_POSSIBLE_STAGES:
                    resolved_csv_cols.append(stoch_col_key)
                else:
                    for csv_k, stage_v in ALL_POSSIBLE_STAGES.items():
                        if stage_v[1] == stoch_col_key:
                            resolved_csv_cols.append(csv_k)
                            break

            # DYNAMIC X-AXIS SCALING ENGINE
            if resolved_csv_cols:
                # Locate the single highest value among the active visible bars
                highest_visible_prob = top_contenders[resolved_csv_cols].max().max()
                # Add a 5% padding buffer for visual breathing room, locked behind a hard 100% ceiling
                x_max_bound = min(100.0, float(highest_visible_prob) * 1.05)
                # Defensive fallback to prevent a 0-width axis error if no data matches
                if x_max_bound <= 0:
                    x_max_bound = 100.0
            else:
                x_max_bound = 100.0

            # 4. Construct the visualization chart
            fig_survival = go.Figure()

            for stoch_col_key in selected_stage_keys:
                if stoch_col_key in ALL_POSSIBLE_STAGES:
                    col_info = ALL_POSSIBLE_STAGES[stoch_col_key]
                    actual_csv_column = stoch_col_key
                else:
                    col_info = None
                    actual_csv_column = None
                    for csv_k, stage_v in ALL_POSSIBLE_STAGES.items():
                        if stage_v[1] == stoch_col_key:
                            col_info = stage_v
                            actual_csv_column = csv_k
                            break

                if col_info and actual_csv_column:
                    fig_survival.add_trace(
                        go.Bar(
                            y=top_contenders["Country"],
                            x=top_contenders[actual_csv_column],
                            name=col_info[1],
                            orientation="h",
                            marker=dict(color=col_info[2]),
                            hovertemplate="%{y} "
                            + col_info[1]
                            + ": <b>%{x:.2f}%</b><extra></extra>",
                        )
                    )

            fig_survival.update_layout(
                title="<b>KNOCKOUT PROGRESSION</b>",
                barmode="group",
                # Injected our adaptive max bound
                xaxis=dict(
                    title="Probability / %", gridcolor="#222222", range=[0, x_max_bound]
                ),
                yaxis=dict(title="", autorange="reversed"),
                legend=dict(
                    orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1
                ),
            )

            fig_survival = apply_mission_control_layout(fig_survival)
            stochastic_visual = mo.as_html(fig_survival)
    stochastic_visual
    return


@app.cell
def _(df_forecast, has_stochastic, mo):
    forecast_table = None
    if has_stochastic and df_forecast is not None:
        # 1. Cleanly round the float vectors for pristine tabular presentation
        display_forecast = df_forecast.copy()
        prob_cols = [c for c in display_forecast.columns if "%" in c]
        display_forecast[prob_cols] = display_forecast[prob_cols].round(2)

        # 2. Wrap dataframe in Marimo's interactive layout engine
        forecast_table = mo.ui.table(
            data=display_forecast,
            pagination=True,
            page_size=10,
        )

        table_panel = mo.md(
            f"""
            ### 🔮 MULTIVERSE PROBABILITY LEDGER
            {forecast_table}
            """
        )
    else:
        table_panel = mo.md("")
    table_panel
    return


@app.cell
def _(df_tables, mo):
    # Identify all active groups parsed by the backend
    available_groups = sorted(df_tables["group"].unique())

    # Spawn a reactive dropdown selector component
    group_dropdown = mo.ui.dropdown(
        options=available_groups, value=available_groups[0], label="GROUP"
    )
    return (group_dropdown,)


@app.cell
def _(DARK_THEME, df_tables, df_tournament, group_dropdown, mo, pd):
    # 1. Extract the reactive value from the dropdown cell
    selected_group = group_dropdown.value

    # 2. Filter down the data matrix
    group_filtered_df = df_tables[df_tables["group"] == selected_group].copy()

    # 3, Clean up the presentation column layout
    group_display_df = (
        group_filtered_df[
            ["position", "team", "points", "goals_for", "goals_against", "goals_diff"]
        ]
        .rename(
            columns={
                "position": "Pos",
                "team": "Country",
                "points": "Pts",
                "goals_for": "GF",
                "goals_against": "GA",
                "goal_difference": "GD",
            }
        )
        .sort_values(by="Pos")
        .reset_index(drop=True)
    )

    # Add top 8 3rd places?

    # 4.Isolate group fixtures for the active dropdown target
    group_label = f"Group {selected_group}"
    group_fixtures_df = df_tournament[df_tournament["round"] == group_label].copy()

    # 5. Chronologically sort by match_id to establish the true round sequence
    group_fixtures_df = group_fixtures_df.sort_values(by="match_id").reset_index(
        drop=True
    )

    # 6. Compute dynamic Matchday indices (2 matches per team round)
    group_fixtures_df["matchday"] = (group_fixtures_df.index // 2) + 1

    # 7. Loop through the 3 matchdays and pre-render the visual templates
    group_tabs_content = {}

    for grp_day in [1, 2, 3]:
        day_matches = group_fixtures_df[group_fixtures_df["matchday"] == grp_day]
        day_cards_html = []

        for _, grp_match in day_matches.iterrows():
            grp_home_team = grp_match["home_team"]
            grp_away_team = grp_match["away_team"]
            grp_h_goals = int(grp_match["predicted_home_goals"])
            grp_a_goals = int(grp_match["predicted_away_goals"])
            grp_winner = grp_match["winner_name_meta"]

            # Symmetrical draw resolution handling with unique scoping
            grp_is_draw = str(grp_winner).lower() in ["draw", "none", "nan", "draws"]

            grp_home_bold = (
                "bold"
                if (grp_winner == grp_home_team and not grp_is_draw)
                else "normal"
            )
            grp_home_color = (
                "#fff" if (grp_winner == grp_home_team or grp_is_draw) else "#888"
            )
            grp_home_crown = (
                "👑 " if (grp_winner == grp_home_team and not grp_is_draw) else ""
            )

            grp_away_bold = (
                "bold"
                if (grp_winner == grp_away_team and not grp_is_draw)
                else "normal"
            )
            grp_away_color = (
                "#fff" if (grp_winner == grp_away_team or grp_is_draw) else "#888"
            )
            grp_away_crown = (
                "👑 " if (grp_winner == grp_away_team and not grp_is_draw) else ""
            )

            grp_venue_tag = (
                f"📍 {grp_match['venue']}" if pd.notna(grp_match.get("venue")) else ""
            )

            grp_card = f"""
            <div style="background-color: {DARK_THEME["paper"]}; border: 1px solid #333; border-radius: 6px; padding: 14px; margin: 8px 0px; font-family: monospace;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 10px; margin-bottom: 6px; display: flex; justify-content: space-between;">
                    <span>🆔 {int(grp_match["match_id"])}</span>
                    <span>{grp_venue_tag}</span>
                </div>
                <div style="font-size: 15px; display: flex; justify-content: space-between; align-items: center; padding: 2px 0;">
                    <span style="font-weight: {grp_home_bold}; color: {grp_home_color};">
                        {grp_home_crown}{grp_home_team}
                    </span>
                    <span style="font-weight: bold; background: #262626; padding: 2px 8px; border-radius: 4px;">{grp_h_goals}</span>
                </div>
                <div style="font-size: 15px; display: flex; justify-content: space-between; align-items: center; padding: 2px 0; margin-bottom: 6px;">
                    <span style="font-weight: {grp_away_bold}; color: {grp_away_color};">
                        {grp_away_crown}{grp_away_team}
                    </span>
                    <span style="font-weight: bold; background: #262626; padding: 2px 8px; border-radius: 4px;">{grp_a_goals}</span>
                </div>
                <div style="border-top: 1px solid #2d2d2d; padding-top: 6px; font-size: 10px; color: {DARK_THEME["accent"]}; display: flex; justify-content: space-between;">
                    <span>📐 Corners: {int(grp_match["corners"])}</span>
                    <span>🟨 Yellows: {int(grp_match["yellow_cards"])}</span>
                    <span>🟥 Reds: {int(grp_match["red_cards"])}</span>
                </div>
            </div>
            """
            day_cards_html.append(grp_card)

        group_tabs_content[f"ROUND {grp_day}"] = mo.Html("".join(day_cards_html))

    # 8. Compile into a neat layout block
    group_match_timeline = mo.ui.tabs(group_tabs_content)

    group_panel = mo.md(
        f"""
        ## 🏟️ DETERMINISTIC HORIZON
        {group_dropdown}
        {mo.ui.table(group_display_df, pagination=False)}

        ### ⚽ GROUP {selected_group} MATCHES
        {group_match_timeline}
        """
    )
    group_panel
    return


@app.cell
def _(DARK_THEME, df_tournament, mo, pd):
    # 1. Dynamically capture all unique rounds that are NOT group stage matches
    all_discovered_rounds = df_tournament["round"].dropna().unique()
    available_rounds = [
        r for r in all_discovered_rounds if not str(r).startswith("Group")
    ]

    # 2. Sort key to keep the tabs tracking in chronological tournament order
    def sort_key(round_name):
        r_lower = str(round_name).lower()
        if "32" in r_lower:
            return 1
        if "16" in r_lower:
            return 2
        if "quarter" in r_lower:
            return 3
        if "semi" in r_lower:
            return 4
        if "third" in r_lower or "3rd" in r_lower:
            return 5
        if "final" in r_lower:
            return 6
        return 7

    available_rounds = sorted(available_rounds, key=sort_key)

    # 3. Pre-render match card layouts for EACH tier into a master tabs dictionary
    tabs_content = {}

    for r in available_rounds:
        round_matches = df_tournament[df_tournament["round"] == r].copy()
        match_cards_html = []

        for _, match in round_matches.iterrows():
            home_team = match["home_team"]
            away_team = match["away_team"]
            h_goals = int(match["predicted_home_goals"])
            a_goals = int(match["predicted_away_goals"])
            winner = match["winner_name_meta"]
            went_to_pens = match.get("penalties", False)
            has_pens = (
                went_to_pens
                if isinstance(went_to_pens, bool)
                else str(went_to_pens).lower() in ["true", "1", "yes"]
            )

            # Compile a subtle styling badge for matches settled from twelve yards
            pens_badge = (
                '<span style="color: #e6739f; background: #2a1b24; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #4c283c; margin-left: 8px; letter-spacing: 0.5px; display: inline-block; vertical-align: middle;">🥅 PENS</span>'
                if has_pens
                else ""
            )

            venue_tag = f"📍 {match['venue']}" if pd.notna(match.get("venue")) else ""

            card = f"""
            <div style="background-color: {DARK_THEME["paper"]}; border: 1px solid #333; border-radius: 6px; padding: 16px; margin: 10px 0px; font-family: monospace;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px; margin-bottom: 8px; display: flex; justify-content: space-between; align-items: center;">
                    <div style="display: flex; align-items: center;">
                        <span>🆔 {int(match["match_id"])}</span>
                        {pens_badge}
                    </div>
                    <span>{venue_tag}</span>
                </div>
                <div style="font-size: 16px; display: flex; justify-content: space-between; align-items: center; padding: 4px 0;">
                    <span style="font-weight: {"bold" if winner == home_team else "normal"}; color: {"#fff" if winner == home_team else "#888"};">
                        {"👑 " if winner == home_team else ""}{home_team}
                    </span>
                    <span style="font-weight: bold; background: #262626; padding: 4px 10px; border-radius: 4px;">{h_goals}</span>
                </div>
                <div style="font-size: 16px; display: flex; justify-content: space-between; align-items: center; padding: 4px 0; margin-bottom: 8px;">
                    <span style="font-weight: {"bold" if winner == away_team else "normal"}; color: {"#fff" if winner == away_team else "#888"};">
                        {"👑 " if winner == away_team else ""}{away_team}
                    </span>
                    <span style="font-weight: bold; background: #262626; padding: 4px 10px; border-radius: 4px;">{a_goals}</span>
                </div>
                <div style="border-top: 1px solid #2d2d2d; padding-top: 8px; font-size: 11px; color: {DARK_THEME["accent"]}; display: flex; justify-content: space-between;">
                    <span>📐 Corners: {int(match["corners"])}</span>
                    <span>🟨 Yellows: {int(match["yellow_cards"])}</span>
                    <span>🟥 Reds: {int(match["red_cards"])}</span>
                </div>
            </div>
            """
            match_cards_html.append(card)

        # Map the pre-compiled layout block to its respective uppercase Tab name
        tabs_content[str(r).upper()] = mo.Html("".join(match_cards_html))

    # 4. Inject the entire mapped dictionary into Marimo's native layout tabs component
    knockout_tabs = mo.ui.tabs(tabs_content)

    # 5. Output the panel view cleanly
    knockout_panel = mo.md(
        f"""
            ---

            ### 💦 KNOCKOUT WATERFALL
            {knockout_tabs}
            """
    )
    knockout_panel
    return


@app.cell
def _(DARK_THEME, df_capabilities, mo):
    # 1. Grab an ordered list of all active countries for our dropdown listings
    all_countries = sorted(df_capabilities["Country"].unique())

    # 2. Instantiate team dropdown selectors
    dropdown_team_a = mo.ui.dropdown(
        options=all_countries,
        value=all_countries[0],  # Default to the first country in the dataset
        label="🏷️ TEAM A",
    )

    dropdown_team_b = mo.ui.dropdown(
        options=all_countries,
        value=all_countries[1]
        if len(all_countries) > 1
        else all_countries[0],  # Default to the second country
        label="🏷️ TEAM B",
    )

    # Render the layout inputs in a side-by-side split container panel
    mo.md(
        f"""
        ---

        ## 🧪 MICRO HORIZON
        ###INTERACTIVE MATCHUP SANDBOX

        <div style="display: flex; gap: 40px; margin: 15px 0;">
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">{dropdown_team_a}</div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">{dropdown_team_b}</div>
        </div>
        """
    )
    return dropdown_team_a, dropdown_team_b


@app.cell
def _(
    DARK_THEME,
    apply_mission_control_layout,
    df_capabilities,
    dropdown_team_a,
    dropdown_team_b,
    go,
    mo,
):
    # 1. Capture current reactive state targets
    team_a = dropdown_team_a.value
    team_b = dropdown_team_b.value

    if team_a == team_b:
        sandbox_output = mo.md(
            "> ⚠️ **Configuration Alert:** Select two distinct country entities to run a comparative matchup profile."
        )
    else:
        # 2. Extract specific data rows from the compiled capabilities lookup table
        stats_a = df_capabilities[df_capabilities["Country"] == team_a].iloc[0]
        stats_b = df_capabilities[df_capabilities["Country"] == team_b].iloc[0]

        # 3. Construct a side-by-side grouped horizontal comparison chart
        # We break metrics into subplots or standardized bars because scales vary (Elo 1800 vs Attack 1.5)
        fig_sandbox = go.Figure()

        # Core capabilities list to parse
        metrics_to_compare = [
            ("Elo_Rating", "Elo Rating"),
            ("Poisson_Attack", "Poisson Attack"),
            ("Poisson_Defense", "Poisson Defense"),
            ("Poisson_Dominance", "Poisson Dominance"),
            ("Short_Term_Form_GF", "Form: Short-term"),
            ("Long_Term_Form_GF", "Form: Long-term"),
        ]

        # Collect values
        labels = [m[1] for m in metrics_to_compare]
        vals_a = [float(stats_a[m[0]]) for m in metrics_to_compare]
        vals_b = [float(stats_b[m[0]]) for m in metrics_to_compare]

        # We normalize values for visual comparison on a single horizontal grid index
        # But print the real numbers inside the text labels for data-density clarity
        max_values = {
            "Elo_Rating": 2100,
            "Poisson_Attack": 3.0,
            "Poisson_Defense": 3.0,
            "Poisson_Dominance": 4.0,
            "Short_Term_Form_GF": 3.0,
            "Long_Term_Form_GF": 3.0,
        }

        norm_a = [
            float(stats_a[m[0]]) / max_values[m[0]] * 100 for m in metrics_to_compare
        ]
        norm_b = [
            float(stats_b[m[0]]) / max_values[m[0]] * 100 for m in metrics_to_compare
        ]

        # Add Team A Vector
        fig_sandbox.add_trace(
            go.Bar(
                y=labels,
                x=norm_a,
                name=team_a,
                orientation="h",
                text=[f"{v:.2f}" if v < 100 else f"{int(v)}" for v in vals_a],
                textposition="inside",
                marker=dict(color=DARK_THEME["accent"]),
                hovertemplate=f"<b>{team_a}</b><br>%{{y}}: %{{text}}<extra></extra>",
            )
        )

        # Add Team B Vector
        fig_sandbox.add_trace(
            go.Bar(
                y=labels,
                x=norm_b,
                name=team_b,
                orientation="h",
                text=[f"{v:.2f}" if v < 100 else f"{int(v)}" for v in vals_b],
                textposition="inside",
                marker=dict(color="#e6739f"),
                hovertemplate=f"<b>{team_b}</b><br>%{{y}}: %{{text}}<extra></extra>",
            )
        )

        fig_sandbox.update_layout(
            title=f"{team_a.upper()} vs {team_b.upper()} - HEAD 2 HEAD CAPABILITIES",
            barmode="group",
            xaxis=dict(title="Relative Strength", showticklabels=False, range=[0, 110]),
            yaxis=dict(autorange="reversed"),
            legend=dict(
                orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1
            ),
        )

        fig_sandbox = apply_mission_control_layout(fig_sandbox)
        sandbox_output = mo.as_html(fig_sandbox)
    sandbox_output
    return


@app.cell
def _(DARK_THEME, apply_mission_control_layout, df_tournament, go, mo, np, pd):
    # 1. Segment the master tournament ledger into distinct execution scopes
    stat_df = df_tournament.copy()
    stat_df["phase"] = np.where(
        stat_df["round"].str.startswith("Group"), "Group Stage", "Knockout Stage"
    )

    # 2. Compute absolute tournament-wide sums for our top KPI block and calculations
    t_matches = len(stat_df)
    t_goals = (
        stat_df["predicted_home_goals"].sum() + stat_df["predicted_away_goals"].sum()
    )
    t_corners = stat_df["corners"].sum()
    t_yellows = stat_df["yellow_cards"].sum()
    t_reds = stat_df["red_cards"].sum()

    # 3. Compute aggregate profiles for each phase
    phase_metrics = []
    for phase_name in ["Group Stage", "Knockout Stage"]:
        phase_sub = stat_df[stat_df["phase"] == phase_name]
        m_count = len(phase_sub)

        if m_count > 0:
            tot_goals = (
                phase_sub["predicted_home_goals"].sum()
                + phase_sub["predicted_away_goals"].sum()
            )
            tot_corners = phase_sub["corners"].sum()
            tot_yellows = phase_sub["yellow_cards"].sum()
            tot_reds = phase_sub["red_cards"].sum()

            phase_metrics.append(
                {
                    "Phase": phase_name,
                    "Matches": m_count,
                    "Avg Goals": tot_goals / m_count,
                    "Avg Corners": tot_corners / m_count,
                    "Avg Yellows": tot_yellows / m_count,
                    "Avg Reds": tot_reds / m_count,
                    "Total Goals": tot_goals,
                    "Total Corners": tot_corners,
                    "Total Yellows": tot_yellows,
                    "Total Reds": tot_reds,
                }
            )

    phase_metrics.append(
        {
            "Phase": "Tournament",
            "Matches": t_matches,
            "Avg Goals": t_goals / t_matches if t_matches > 0 else 0,
            "Avg Corners": t_corners / t_matches if t_matches > 0 else 0,
            "Avg Yellows": t_yellows / t_matches if t_matches > 0 else 0,
            "Avg Reds": t_reds / t_matches if t_matches > 0 else 0,
            "Total Goals": t_goals,
            "Total Corners": t_corners,
            "Total Yellows": t_yellows,
            "Total Reds": t_reds,
        }
    )

    df_analytics = pd.DataFrame(phase_metrics)
    # Drop redundant red card series from table
    df_table_view = df_analytics.drop(
        columns=["Avg Reds", "Total Reds"], errors="ignore"
    )

    # 4. Isolate only stage divisions for graph plotting (drops the Total summary row)
    df_graph = df_analytics[df_analytics["Phase"] != "Tournament"].copy()

    # 5. Generate high-fidelity Plotly grouped comparisons for per-game rates
    fig_analytics = go.Figure()

    rate_columns = [
        ("Avg Goals", "Goals", "#00adb5"),
        ("Avg Corners", "Corners", "#1f4068"),
        ("Avg Yellows", "Yellow Cards", "#f4b41a"),
        # ("Avg Reds", "Red Cards", "#e6739f")  # Commented out: red is hard-coded zero
    ]

    for col_key, col_label, col_color in rate_columns:
        fig_analytics.add_trace(
            go.Bar(
                x=df_graph["Phase"],
                y=df_graph[col_key],
                name=col_label,
                text=df_graph[col_key].round(2),
                textposition="auto",
                marker=dict(color=col_color),
                hovertemplate="%{x} " + col_label + ": <b>%{y:.2f}</b><extra></extra>",
            )
        )

    fig_analytics.update_layout(
        title="<b>GROUP & KNOCKOUT METRICS</b>",
        barmode="group",
        xaxis=dict(title=""),
        yaxis=dict(title="Per Game Average Metric", gridcolor="#222222"),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    fig_analytics = apply_mission_control_layout(fig_analytics)

    # 6. Compile layout view with responsive KPI markdown styling cards
    mo.md(
        f"""
        ---

        ## 📈 TOURNAMENT ANALYTICS HUB
        <div style="display: flex; gap: 15px; margin: 20px 0; text-align: center; font-family: monospace;">
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">TOTAL MATCHES</div>
                <div style="font-size: 22px; font-weight: bold; color: #fff;">{t_matches}</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">TOTAL GOALS</div>
                <div style="font-size: 22px; font-weight: bold; color: #00adb5;">{t_goals}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_goals / t_matches).round(2)} / game</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">TOTAL CORNERS</div>
                <div style="font-size: 22px; font-weight: bold; color: #1f4068;">{t_corners}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_corners / t_matches).round(2)} / game</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">YELLOW CARDS</div>
                <div style="font-size: 22px; font-weight: bold; color: #f4b41a;">{t_yellows}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_yellows / t_matches).round(2)} / game</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">RED CARDS</div>
                <div style="font-size: 22px; font-weight: bold; color: #e6739f;">{t_reds}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_reds / t_matches).round(2)} / game</div>
            </div>
        </div>

        {mo.as_html(fig_analytics)}

        #### 📋 STATISTICS
        {mo.ui.table(df_table_view.round(3), pagination=False)}
        """
    )
    return


if __name__ == "__main__":
    app.run()
