# pyright: reportUnusedExpression=false
# ruff: noqa: B018

"""🏆 FIFA World Cup 2026 Prediction & Simulation Dashboard.

This module orchestrates a reactive front-end dashboard built natively in Marimo,
designed to ingest, evaluate, and visualize predictive outputs generated by the
underlying multi-model ensemble pipeline.

Execution Vectors:
    $ uv run marimo edit dashboard.py
    $ uv run marimo run dashboard.py

Dashboard Layout Matrix:
    1. 🚀 PARAMETER METRIC BANNER & CONTROL NODE
        Orchestrates run dropdown selectors, global view toggles (Stochastic
        vs. Deterministic), active engine variables, and consensus weights.

    2. 🧪 MICRO HORIZON SANDBOX
        Executes isolated head-to-head simulations on pure neutral ground.
        Renders an adaptive match outcome card with distribution bars.
        Displays a beautiful Plotly radar with head 2 head capabilities.

    3. 🎲 STOCHASTIC PROGRESSION CHART
        Generates responsive horizontal survival charts via Plotly, driving
        granular predictive trends based on selected tournament tiers and
        squad depth parameters.

    4. 🏟️ GROUP STAGE
        Evaluates active group standings tables—dynamically transitioning
        between deterministic points and expected stochastic xPts/xGD metrics—
        coupled with reactive multi-round match timeline cards.

    5. 💦 KNOCKOUT WATERFALL
        Tracks real-time vertical bracket flows using tabbed knockout nodes.
        Visualizes dual-mode resolution vectors spanning exact deterministic
        timelines or 3-phase probability lines.

    6. 📈 TOURNAMENT ANALYTICS
        Aggregates global performance metrics into operational KPI banners,
        paired with group-stage vs knockout-stage chart and tracking array.

    7. 🔮 MULTIVERSE LEDGER & WILDCARDS
        Deep-dives into raw percentage matrices. Houses the complete multi-phase
        probabilistic forecasting tables and 3rd place wildcard advancement ledgers.

Design Considerations:
    - This file explicitly silences 'unused-expression' warnings via file-level
      Pyright and Ruff directives to accommodate Marimo's terminal layout pattern.
    - Uses highly scoped responsive container components to guarantee dark-mode
      visual parity and strict monospaced numerical alignment.
"""

import marimo

__generated_with = "0.23.10"
app = marimo.App(width="medium", app_title="fifa-world-cup-2026-predictor")


@app.cell
def _():
    import glob
    import json
    import os

    import marimo as mo
    import pandas as pd
    import plotly.graph_objects as go

    # Define styling palette
    DARK_THEME = {
        "background": "#121212",
        "paper": "#1e1e1e",
        "text": "#e0e0e0",
        "accent": "#00adb5",
        "muted": "#6c757d",
    }

    # Apply global custom overrides to Plotly dark layout defaults
    def apply_mission_control_layout(fig):
        fig.update_layout(
            template="plotly_dark",
            paper_bgcolor=DARK_THEME["paper"],
            plot_bgcolor=DARK_THEME["background"],
            font=dict(color=DARK_THEME["text"], family="JetBrains Mono, monospace"),
            title=dict(
                font=dict(
                    family="'Inter', 'Segoe UI', system-ui, sans-serif",
                    size=16,
                    weight="bold",
                )
            ),
            margin=dict(l=40, r=40, t=50, b=40),
        )

        return fig

    return DARK_THEME, apply_mission_control_layout, glob, go, json, mo, os, pd


@app.cell
def _(DARK_THEME, mo):
    # ⚡ GLOBAL CSS INJECTION LAYER
    global_styles = mo.Html(
        f"""
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');

            .marimo-output h1, h1 {{
                font-family: 'Inter', 'Segoe UI', system-ui, sans-serif !important;
                font-weight: 800 !important;
                letter-spacing: -1.5px !important;
                color: #ffffff !important;
            }}

            .marimo-output h2, h2 {{
                font-family: 'Inter', 'Segoe UI', system-ui, sans-serif !important;
                font-weight: 700 !important;
                letter-spacing: -1px !important;
                color: #ffffff !important;
                border-bottom: 1px solid #2d2d2d !important;
                padding-bottom: 8px !important;
            }}

            .marimo-output h3, h3, .marimo-output h4, h4 {{
                font-family: 'Inter', 'Segoe UI', system-ui, sans-serif !important;
                font-weight: 600 !important;
                letter-spacing: -0.5px !important;
                color: {DARK_THEME["accent"]} !important;
            }}

            .marimo-output p, p {{
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif !important;
                color: {DARK_THEME["text"]} !important;
                font-size: 14px !important;
                line-height: 1.6 !important;
            }}

            /* LAYER A: STANDARD MARKDOWN TABLES - CHANGED TO 100% MAX-WIDTH */
            .marimo-output table:not([class*="marimo"]) {{
                width: 100% !important;
                max-width: 100% !important;
                margin: 15px 0 !important;
                border-collapse: collapse !important;
            }}

            .marimo-output table:not([class*="marimo"]) th {{
                padding: 10px 16px !important;
                font-size: 13px !important;
                font-family: 'Inter', sans-serif !important;
                background-color: #1a1a1a !important;
                color: #ffffff !important;
                text-align: left !important;
                border-bottom: 2px solid #333 !important;
            }}

            .marimo-output table:not([class*="marimo"]) td {{
                padding: 10px 16px !important;
                font-size: 13px !important;
                font-family: -apple-system, BlinkMacSystemFont, sans-serif !important;
                color: {DARK_THEME["text"]} !important;
                border-bottom: 1px solid #262626 !important;
            }}

            .marimo-output table:not([class*="marimo"]) td code {{
                font-family: 'JetBrains Mono', monospace !important;
                font-size: 12px !important;
                background: #262626 !important;
                padding: 2px 6px !important;
                border-radius: 4px !important;
            }}

            /* LAYER B: GLOBAL HIGH-DENSITY INTERACTIVE DATA TABLES */
            marimo-table, [data-testid="ns-table"], div[class*="table-wrapper"] {{
                width: 100% !important;
                max-width: 100% !important;
            }}

            marimo-table th, [data-testid="ns-table"] th, div[class*="table"] th {{
                padding: 4px 6px !important;
                font-size: 11px !important;
                font-family: 'Inter', sans-serif !important;
                font-weight: 700 !important;
                background-color: #151515 !important;
                white-space: normal !important;
                word-break: break-word !important;
                line-height: 1.2 !important;
                vertical-align: bottom !important;
            }}

            marimo-table td, [data-testid="ns-table"] td, div[class*="table"] td {{
                padding: 4px 6px !important;
                font-size: 11px !important;
                font-family: 'JetBrains Mono', monospace !important;
                line-height: 1.2 !important;
            }}

            div[class*="table"] div, div[class*="grid"] div {{
                gap: 1px !important;
            }}
        </style>
        """
    )

    global_styles
    return


@app.cell
def _(glob, mo, os):
    # 1. Discover all execution folders by true chronological modification time
    all_runs = sorted(
        glob.glob(os.path.join("data", "runs", "run_*")), key=os.path.getmtime
    )
    if not all_runs:
        raise FileNotFoundError(
            "❌ Operational error: No simulation artifacts found in data/runs/."
        )

    # 2. Extract clean string folder names (basenames)
    run_names = [os.path.basename(r) for r in all_runs]

    # 3. Reverse the array order so the newest runs appear at the top of the dropdown list
    run_choices = list(reversed(run_names))

    # 4. Target the clean string name of the newest run as the default option
    latest_run_name = run_names[-1]

    # 5. Instantiate the dropdown using the foolproof string list strategy
    run_dropdown = mo.ui.dropdown(
        options=run_choices,
        value=latest_run_name,
        label="📂 SELECT SIMULATION",
    )
    return (run_dropdown,)


@app.cell
def _(json, os, pd, run_dropdown):
    # 1. Get the clean folder name string from the dropdown selection state
    run_id = run_dropdown.value

    # 2. Explicitly reconstruct the accurate path relative to project root
    active_run_dir = os.path.join("data", "runs", run_id)

    # 3. Ingest selected run datasets into active dashboard scope
    df_tournament = pd.read_csv(
        os.path.join(active_run_dir, "deterministic_tournament.csv")
    )
    df_tables = pd.read_csv(
        os.path.join(active_run_dir, "deterministic_group_tables.csv")
    )
    df_thirds = pd.read_csv(
        os.path.join(active_run_dir, "deterministic_third_places.csv")
    )
    df_capabilities = pd.read_csv(
        os.path.join(active_run_dir, "pre_tournament_capabilities.csv")
    )

    # UN-FLOODABLE DETERMINISTIC DISCIPLINARY IMPUTATION HACK
    # Selects exactly the top 10 highest-fouling matches in the entire tournament layout
    if "red_cards" in df_tournament.columns:
        # 1. Reset all matches to zero
        df_tournament["red_cards"] = 0

        # 2. Sort the tournament by yellow cards descending, using match_id as a tie-breaker
        # to find the exact 10 most aggressive games
        top_fiery_indices = (
            df_tournament.sort_values(
                by=["yellow_cards", "match_id"], ascending=[False, True]
            )
            .head(10)
            .index
        )

        # 3. Inject exactly 1 red card into only those 10 specific rows
        df_tournament.loc[top_fiery_indices, "red_cards"] = 1

    # Defensive infrastructure fallback if auditing older run branches
    matchups_path = os.path.join(active_run_dir, "stochastic_sandbox_matchups.csv")
    if os.path.exists(matchups_path):
        df_matchups = pd.read_csv(matchups_path)
    else:
        df_matchups = pd.DataFrame(
            columns=[
                "home_team",
                "away_team",
                "venue_country",
                "ensemble_lambda_home",
                "ensemble_lambda_away",
            ]
        )

    # Safely unpack optional stochastic Data
    forecast_path = os.path.join(active_run_dir, "stochastic_forecast.csv")
    df_forecast = pd.read_csv(forecast_path) if os.path.exists(forecast_path) else None

    xtables_path = os.path.join(active_run_dir, "stochastic_group_tables.csv")
    df_xtables = pd.read_csv(xtables_path) if os.path.exists(xtables_path) else None

    stoch_tourn_path = os.path.join(active_run_dir, "stochastic_tournament.csv")
    df_tournament_stoch = (
        pd.read_csv(stoch_tourn_path) if os.path.exists(stoch_tourn_path) else None
    )

    has_stochastic = os.path.exists(forecast_path)

    # 4. Parse running parameters from JSON configuration sheet
    with open(os.path.join(active_run_dir, "metadata.json"), "r") as f:
        metadata = json.load(f)

    config = metadata["config"]
    weights = metadata["ensemble_weights"]
    match_rules = metadata.get(
        "match_rules", {"et_multiplier": 1.0 / 3.0, "fatigue_factor": 0.80}
    )
    return (
        config,
        df_capabilities,
        df_forecast,
        df_matchups,
        df_tables,
        df_thirds,
        df_tournament,
        df_tournament_stoch,
        df_xtables,
        has_stochastic,
        match_rules,
        run_id,
        weights,
    )


@app.cell
def _(config, has_stochastic, mo, run_dropdown, run_id, weights):
    # 1. Resolve Monte Carlo Engine Live Status Flags
    mc_active = config.get("run_monte_carlo", False)
    mc_badge_color = "#34A853" if mc_active else "#EA4335"

    if mc_active:
        mc_text = f"🟢 ACTIVE<br><span style='font-size: 12px; color: #888;'>{config.get('monte_carlo_runs', 0):,} Universes</span>"
    else:
        mc_text = "🔴 DISABLED<br><span style='font-size: 12px; color: #888;'></span>"

    # 2. Create the Global Render Toggle
    view_opts = (
        ["🎲 Stochastic", "🎯 Deterministic"]
        if has_stochastic
        else ["🎯 Deterministic"]
    )
    view_mode_toggle = mo.ui.radio(
        options=view_opts, value=view_opts[0], label="🌐 RENDER MODE", inline=True
    )

    # 3. Render the top-level app header title
    title_panel = mo.md("# 🚀 FIFA WORLD CUP 2026 PREDICTOR")

    # 4. Render the control bar (Dropdown + Render Mode switch)
    controls_panel = mo.md(
        f"""
        <div style="background: #1a1a1a; padding: 14px; border-radius: 6px; border: 1px solid #00adb5; margin: 20px 0; display: flex; gap: 40px; align-items: center;">
            <div style="flex: 1;">{run_dropdown}</div>
            <div style="flex: 1;">{view_mode_toggle}</div>
        </div>
        """
    )

    # 5 Left Column: Active Run Identifier Card
    profile_card = mo.md(
        f"""
        <div style="background: #1a1a1a; padding: 20px 16px; border-radius: 6px; border: 1px solid #2d2d2d; font-family: monospace; text-align: center; height: 142px; display: flex; flex-direction: column; justify-content: center; margin-top: 0px; box-sizing: border-box;">
            <span style="color: #00adb5; font-size: 18px; font-weight: bold; word-break: break-all; line-height: 1.3;">📊 {run_id}</span>
        </div>
        """
    )

    # 6. Middle Column: High-Density HTML Table (Centered middle-middle via inline Flexbox)
    _table_panel = mo.md(
        f"""
        <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 142px; width: 100%; box-sizing: border-box; background: #1a1a1a; border-radius: 6px; border: 1px solid #2d2d2d; padding: 12px;">
            <table style="width: auto !important; border-collapse: collapse; font-family: monospace; font-size: 13px; margin: 0 auto; background: transparent;">
                <thead>
                    <tr style="border-bottom: 2px solid #333;">
                        <th style="padding: 4px 10px; text-align: left; background: transparent; color: #fff; font-weight: bold; border-bottom: 2px solid #333 !important;">Ensemble Model</th>
                        <th style="padding: 4px 10px; text-align: right; background: transparent; color: #fff; font-weight: bold; border-bottom: 2px solid #333 !important;">Weight</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style="border-bottom: 1px solid #262626;">
                        <td style="padding: 6px 10px; text-align: left; border-bottom: 1px solid #262626 !important;">🧮 Poisson Joint MLE</td>
                        <td style="padding: 6px 10px; text-align: right; color: #00adb5; font-weight: bold; border-bottom: 1px solid #262626 !important;">{weights["poisson"]:.3f}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid #262626;">
                        <td style="padding: 6px 10px; text-align: left; border-bottom: 1px solid #262626 !important;">📈 Dynamic ELO Rating</td>
                        <td style="padding: 6px 10px; text-align: right; color: #00adb5; font-weight: bold; border-bottom: 1px solid #262626 !important;">{weights["elo"]:.3f}</td>
                    </tr>
                    <tr>
                        <td style="padding: 6px 10px; text-align: left; border-bottom: none !important;">🌲 XGBoost Count Regressor</td>
                        <td style="padding: 6px 10px; text-align: right; color: #00adb5; font-weight: bold; border-bottom: none !important;">{weights["xgb"]:.3f}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        """
    )

    # 7. Right Column: Monte Carlo Status Indicator Card
    mc_card = mo.md(
        f"""
        <div style="background: #1a1a1a; padding: 20px 18px; border-radius: 6px; border: 1px solid #2d2d2d; font-family: monospace; text-align: center; height: 142px; display: flex; flex-direction: column; justify-content: center; margin-top: 0px; box-sizing: border-box;">
            <div style="color: #6c757d; font-size: 14px; font-weight: bold; margin-bottom: 4px; letter-spacing: 0.5px;">🎲 MONTE CARLO ENGINE</div>
            <span style="color: {mc_badge_color}; font-size: 18px; font-weight: bold; line-height: 1.4;">{mc_text}</span>
        </div>
        """
    )

    # 8. Bind all three columns side-by-side into a proportional layout grid
    lower_grid = mo.hstack(
        [profile_card, _table_panel, mc_card], widths=[1, 1, 1], gap=1.5
    )

    # 9. Stack the entire panel structure vertically
    header_panel = mo.vstack([title_panel, controls_panel, lower_grid])

    header_panel
    return (view_mode_toggle,)


@app.cell
def _(DARK_THEME, df_capabilities, has_stochastic, mo):
    all_countries = sorted(df_capabilities["Country"].unique())

    team_a_ctrl = mo.ui.dropdown(
        options=all_countries, value=all_countries[1], label="🏷️ TEAM A"
    )
    team_b_ctrl = mo.ui.dropdown(
        options=all_countries,
        value=all_countries[40] if len(all_countries) > 40 else all_countries[0],
        label="🏷️ TEAM B",
    )
    is_ko_ctrl = mo.ui.checkbox(label="🏆 Knockout", value=False)

    is_stoch_ctrl = mo.ui.checkbox(
        label="🎲 Stochastic", value=has_stochastic, disabled=not has_stochastic
    )

    layout_text = f"""
    <div style="background: {DARK_THEME["paper"]}; padding: 20px; border-radius: 6px; border: 1px solid #333;">
        <div style="display: flex; gap: 20px; margin-bottom: 15px;">
            <div style="flex: 1;">{{team_a}}</div>
            <div style="flex: 1;">{{team_b}}</div>
        </div>
        <div style="display: flex; justify-content: space-between; align-items: center; border-top: 1px solid #2d2d2d; padding-top: 15px;">
            <div style="font-weight: bold; color: {DARK_THEME["accent"]}; font-size: 16px; font-family: monospace; letter-spacing: 0.5px;">
                ⚔️ INTERACTIVE MATCHUP SANDBOX 🛡️
            </div>
            <div style="display: flex; gap: 30px;">
                {{is_ko}}
                {{is_stoch}}
            </div>
        </div>
    </div>
    """

    sandbox_layout = mo.md(layout_text).batch(
        team_a=team_a_ctrl, team_b=team_b_ctrl, is_ko=is_ko_ctrl, is_stoch=is_stoch_ctrl
    )

    sandbox_form = sandbox_layout.form(
        bordered=False,
        submit_button_label="⚡ RUN SIMULATION",
        submit_button_tooltip="Execute neutral match!",
    )

    ui_panel = mo.vstack([sandbox_form])
    ui_panel
    return (sandbox_form,)


@app.cell
def _(
    DARK_THEME,
    df_matchups,
    has_stochastic,
    json,
    match_rules,
    mo,
    sandbox_form,
):
    mo.stop(sandbox_form.value is None, mo.md(""))

    sim_data = sandbox_form.value
    sim_team_a = sim_data["team_a"]
    sim_team_b = sim_data["team_b"]
    is_ko = sim_data["is_ko"]
    is_stoch = sim_data.get("is_stoch", False) and has_stochastic

    mo.stop(
        sim_team_a == sim_team_b,
        mo.md("> ⚠️ **Simulation Error:** A team cannot play itself."),
    )

    # 1. Coordinate Pair Ingestion
    match_row = df_matchups[
        (df_matchups["home_team"] == sim_team_a)
        & (df_matchups["away_team"] == sim_team_b)
        & (df_matchups["venue_country"] == "Neutral")
    ]
    _is_swapped = False

    if match_row.empty:
        match_row = df_matchups[
            (df_matchups["home_team"] == sim_team_b)
            & (df_matchups["away_team"] == sim_team_a)
            & (df_matchups["venue_country"] == "Neutral")
        ]
        if not match_row.empty:
            _is_swapped = True

    # 🛑 DEFENSIBLY CHECK FOR MISSING SANDBOX DATA WITHOUT CRASHING THE NODE
    if match_row.empty:
        card_html = f"""
        <div style="background-color: {DARK_THEME["paper"]}; border: 1px solid #333; border-radius: 6px; padding: 24px; margin-top: 20px; font-family: monospace; text-align: center; max-width: 100%;">
            <div style="font-size: 13px; color: {DARK_THEME["muted"]}; font-weight: bold; margin-bottom: 8px; letter-spacing: 0.5px;">🏟️ MATCH SIMULATION CARD UNAVAILABLE</div>
            <div style="font-size: 11px; color: #888; line-height: 1.6;">
                The simulation sandbox cache was not generated for this run sequence.<br>
                To activate live scorelines and win probabilities, ensure
                <code style="background: #262626; padding: 2px 6px; border-radius: 4px; color: #00adb5; font-family: monospace;">RUN_MONTE_CARLO = True</code> is enabled in <code style="color: #fff;">main.py</code>.
            </div>
        </div>
        """
    else:
        row_data = match_row.iloc[0]
        discovered_venue = row_data.get("venue_country", "Neutral Turf")

        # 2. Extract baseline continuous xG values
        if not _is_swapped:
            lambda_a = float(row_data["ensemble_lambda_home"])
            lambda_b = float(row_data["ensemble_lambda_away"])
        else:
            lambda_a = float(row_data["ensemble_lambda_away"])
            lambda_b = float(row_data["ensemble_lambda_home"])

        # 3. Compile Core Match Card Render Resolution Layer
        _match_resolution_html = ""
        _et_badge = ""
        _pens_badge = ""
        stoch_footer_html = ""

        if is_stoch:
            # --- STOCHASTIC PROBABILITY BAR GENERATION ---
            if is_ko:
                _h90 = float(
                    row_data[
                        "ko_win_90_away_pct" if _is_swapped else "ko_win_90_home_pct"
                    ]
                )
                _h120 = float(
                    row_data[
                        "ko_win_120_away_pct" if _is_swapped else "ko_win_120_home_pct"
                    ]
                )
                _hpen = float(
                    row_data[
                        "ko_win_pen_away_pct" if _is_swapped else "ko_win_pen_home_pct"
                    ]
                )

                _a90 = float(
                    row_data[
                        "ko_win_90_home_pct" if _is_swapped else "ko_win_90_away_pct"
                    ]
                )
                _a120 = float(
                    row_data[
                        "ko_win_120_home_pct" if _is_swapped else "ko_win_120_away_pct"
                    ]
                )
                _apen = float(
                    row_data[
                        "ko_win_pen_home_pct" if _is_swapped else "ko_win_pen_away_pct"
                    ]
                )

                _h_tot = _h90 + _h120 + _hpen
                _a_tot = _a90 + _a120 + _apen
                _w90, _w120, _wpen = _h90 + _a90, _h120 + _a120, _hpen + _apen

                _match_resolution_html = f"""
                <div style="display: flex; justify-content: space-between; font-weight: bold; font-size: 16px; padding-bottom: 12px; border-bottom: 1px solid #2d2d2d;">
                    <span style="color: {DARK_THEME["accent"]};">{sim_team_a} ({_h_tot:.1f}%)</span>
                    <span style="color: #666; font-size: 12px;">vs</span>
                    <span style="color: #e6739f;">({_a_tot:.1f}%) {sim_team_b}</span>
                </div>

                <div style="margin-top: 12px; margin-bottom: 8px;">
                    <div style="display: flex; justify-content: space-between; font-size: 10px; margin-bottom: 2px;">
                        <span style="color: {DARK_THEME["accent"]}>{_h90:.1f}%</span>
                        <span style="color: #888; font-weight: bold; letter-spacing: 0.5px;">90 MIN ({_w90:.1f}%)</span>
                        <span style="color: #e6739f;">{_a90:.1f}%</span>
                    </div>
                    <div style="display: flex; height: 6px; border-radius: 3px; overflow: hidden; background: #262626;">
                        <div style="width: {(_h90 / _w90 * 100) if _w90 > 0 else 0}%; background: {DARK_THEME["accent"]};"></div>
                        <div style="width: {(_a90 / _w90 * 100) if _w90 > 0 else 0}%; background: #e6739f;"></div>
                    </div>
                </div>

                <div style="margin-bottom: 8px;">
                    <div style="display: flex; justify-content: space-between; font-size: 10px; margin-bottom: 2px;">
                        <span style="color: {DARK_THEME["accent"]}>{_h120:.1f}%</span>
                        <span style="color: #888; font-weight: bold; letter-spacing: 0.5px;">⏱️ EXTRA TIME ({_w120:.1f}%)</span>
                        <span style="color: #e6739f;">{_a120:.1f}%</span>
                    </div>
                    <div style="display: flex; height: 6px; border-radius: 3px; overflow: hidden; background: #262626;">
                        <div style="width: {(_h120 / _w120 * 100) if _w120 > 0 else 0}%; background: {DARK_THEME["accent"]};"></div>
                        <div style="width: {(_a120 / _w120 * 100) if _w120 > 0 else 0}%; background: #e6739f;"></div>
                    </div>
                </div>

                <div style="margin-bottom: 4px;">
                    <div style="display: flex; justify-content: space-between; font-size: 10px; margin-bottom: 2px;">
                        <span style="color: {DARK_THEME["accent"]}>{_hpen:.1f}%</span>
                        <span style="color: #888; font-weight: bold; letter-spacing: 0.5px;">🥅 PENALTIES ({_wpen:.1f}%)</span>
                        <span style="color: #e6739f;">{_apen:.1f}%</span>
                    </div>
                    <div style="display: flex; height: 6px; border-radius: 3px; overflow: hidden; background: #262626;">
                        <div style="width: {(_hpen / _wpen * 100) if _wpen > 0 else 0}%; background: {DARK_THEME["accent"]};"></div>
                        <div style="width: {(_apen / _wpen * 100) if _wpen > 0 else 0}%; background: #e6739f;"></div>
                    </div>
                </div>
                """
            else:
                _raw_g_h = float(row_data["grp_win_home"])
                _raw_g_a = float(row_data["grp_win_away"])
                wins_a = _raw_g_a if _is_swapped else _raw_g_h
                wins_b = _raw_g_h if _is_swapped else _raw_g_a
                draws = float(row_data["grp_draw"])

                _match_resolution_html = f"""
                <div style="display: flex; flex-direction: column; gap: 8px; padding: 4px 0;">
                    <div style="display: flex; justify-content: space-between; font-weight: bold; font-size: 16px;">
                        <span style="color: {DARK_THEME["accent"]};">{sim_team_a}</span>
                        <span style="color: #666; font-size: 11px;">vs</span>
                        <span style="color: #e6739f;">{sim_team_b}</span>
                    </div>
                    <div style="display: flex; height: 8px; border-radius: 4px; overflow: hidden; background: #262626;">
                        <div style="width: {wins_a}%; background: {DARK_THEME["accent"]};"></div>
                        <div style="width: {draws}%; background: {DARK_THEME["muted"]};"></div>
                        <div style="width: {wins_b}%; background: #e6739f;"></div>
                    </div>
                    <div style="display: flex; justify-content: space-between; font-size: 11px; color: #ccc;">
                        <span>Home Win: <b>{wins_a:.1f}%</b></span>
                        <span style="color: #888;">DRAW {draws:.1f}%</span>
                        <span>Away Win: <b>{wins_b:.1f}%</b></span>
                    </div>
                </div>
                """

            top_scores = json.loads(row_data["top_scorelines_json"])
            score_cards = []
            for rank_idx, score_data in enumerate(top_scores):
                score_line = score_data["score"]
                score_pct = float(score_data["pct"])
                if _is_swapped and "-" in score_line:
                    score_line = "-".join(
                        [s.strip() for s in reversed(score_line.split("-"))]
                    )

                score_cards.append(f"""
                    <div style="flex: 1; background: #1a1a1a; padding: 10px; border-radius: 4px; border: 1px solid #2d2d2d; text-align: center;">
                        <div style="font-size: 10px; color: {DARK_THEME["muted"]}; margin-bottom: 2px; font-weight: bold;">RANK #{rank_idx + 1}</div>
                        <div style="font-size: 15px; font-weight: bold; color: #fff; margin-bottom: 4px; font-family: monospace;">{score_line}</div>
                        <div style="font-size: 11px; font-weight: bold;">{score_pct:.1f}%</div>
                    </div>
                """)

            stoch_footer_html = f"""
            <div style="border-top: 1px solid #2d2d2d; margin-top: 15px; padding-top: 12px;">
                <div style="font-size: 10px; color: {DARK_THEME["muted"]}; margin-bottom: 6px; font-weight: bold; letter-spacing: 0.25px;">⚽ TOP 3 EXPECTED SCORELINES (90 Min)</div>
                <div style="display: flex; gap: 10px;">
                    {"".join(score_cards)}
                </div>
            </div>
            """
        else:
            # --- DETERMINISTIC OUTCOME RENDER ---
            pred_a_goals = int(round(lambda_a))
            pred_b_goals = int(round(lambda_b))
            sim_winner = "Draw"
            if pred_a_goals > pred_b_goals:
                sim_winner = sim_team_a
            elif pred_b_goals > pred_a_goals:
                sim_winner = sim_team_b

            if is_ko and sim_winner == "Draw":
                et_multiplier = match_rules.get("et_multiplier", 1.0 / 3.0)
                fatigue_factor = match_rules.get("fatigue_factor", 0.80)
                raw_a_120 = lambda_a * (1.0 + (et_multiplier * fatigue_factor))
                raw_b_120 = lambda_b * (1.0 + (et_multiplier * fatigue_factor))
                pred_a_goals = int(round(raw_a_120))
                pred_b_goals = int(round(raw_b_120))

                if pred_a_goals > pred_b_goals:
                    sim_winner = sim_team_a
                    _et_badge = '<span style="color: #ff7b54; background: #2a1e1b; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #542e23; margin-left: 8px;">⏱️ ET</span>'
                elif pred_b_goals > pred_a_goals:
                    sim_winner = sim_team_b
                    _et_badge = '<span style="color: #ff7b54; background: #2a1e1b; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #542e23; margin-left: 8px;">⏱️ ET</span>'
                else:
                    sim_winner = sim_team_a if lambda_a >= lambda_b else sim_team_b
                    _pens_badge = '<span style="color: #e6739f; background: #2a1b24; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #4c283c; margin-left: 8px;">🥅 PENS</span>'

            _match_resolution_html = f"""
            <div style="font-size: 18px; display: flex; justify-content: space-between; align-items: center; padding: 6px 0;">
                <span style="font-weight: {"bold" if sim_winner == sim_team_a else "normal"}; color: {"#fff" if sim_winner == sim_team_a else "#888"};">
                    {"👑 " if sim_winner == sim_team_a else ""}{sim_team_a}
                </span>
                <span style="font-weight: bold; background: #262626; padding: 4px 12px; border-radius: 4px;">{pred_a_goals}</span>
            </div>
            <div style="font-size: 18px; display: flex; justify-content: space-between; align-items: center; padding: 6px 0; margin-bottom: 8px;">
                <span style="font-weight: {"bold" if sim_winner == sim_team_b else "normal"}; color: {"#fff" if sim_winner == sim_team_b else "#888"};">
                    {"👑 " if sim_winner == sim_team_b else ""}{sim_team_b}
                </span>
                <span style="font-weight: bold; background: #262626; padding: 4px 12px; border-radius: 4px;">{pred_b_goals}</span>
            </div>
            """

        card_html = f"""
        <div style="background-color: {DARK_THEME["paper"]}; border: 1px solid #00adb5; border-radius: 6px; padding: 16px; margin-top: 20px; font-family: monospace; max-width: 100%;">
            <div style="font-size: 11px; margin-bottom: 12px; display: flex; justify-content: space-between; align-items: center; font-weight: bold;">
                <div style="display: flex; align-items: center;">
                    <span>⚡ LIVE MATCHUP</span>
                    {_et_badge}
                    {_pens_badge}
                </div>
                <span>📍 {discovered_venue} Turf</span>
            </div>

            {_match_resolution_html}

            <div style="border-top: 1px solid #2d2d2d; margin-top: 10px; padding-top: 10px; font-size: 12px; color: {DARK_THEME["muted"]}; display: flex; justify-content: space-between;">
                <span title="Base Expected Goals parameters">💡 Model xG: {lambda_a:.2f} - {lambda_b:.2f}</span>
                <span>⚖️ Absolute Edge: {abs(lambda_a - lambda_b):.2f}</span>
            </div>

            {stoch_footer_html}
        </div>
        """

    simulation_output = mo.Html(card_html)
    simulation_output
    return


@app.cell
def _(
    DARK_THEME,
    apply_mission_control_layout,
    df_capabilities,
    go,
    mo,
    sandbox_form,
):
    mo.stop(
        sandbox_form.value is None,
        mo.md(""),
    )

    team_a = sandbox_form.value["team_a"]
    team_b = sandbox_form.value["team_b"]

    if team_a == team_b:
        sandbox_output = mo.md(
            "> ⚠️ **Configuration Alert:** Select two distinct country entities to run a comparative matchup profile."
        )
    else:
        stats_a = df_capabilities[df_capabilities["Country"] == team_a].iloc[0]
        stats_b = df_capabilities[df_capabilities["Country"] == team_b].iloc[0]

        fig_sandbox = go.Figure()

        # 1. PRE-COMPUTE GLOBAL COHORT BOUNDARIES FOR DYNAMIC SCALING
        # Elo Base
        elo_min, elo_max = (
            df_capabilities["Elo_Rating"].min(),
            df_capabilities["Elo_Rating"].max(),
        )

        # Poisson Attack & Defense
        atk_min, atk_max = (
            df_capabilities["Poisson_Attack"].min(),
            df_capabilities["Poisson_Attack"].max(),
        )
        def_min, def_max = (
            df_capabilities["Poisson_Defense"].min(),
            df_capabilities["Poisson_Defense"].max(),
        )

        # Elo Momentum (Signed)
        mom_min, mom_max = (
            df_capabilities["Elo_Momentum"].min(),
            df_capabilities["Elo_Momentum"].max(),
        )

        # Volatilities (Short-term CVs)
        v_atk_min, v_atk_max = (
            df_capabilities["Attack_Volatility_Short"].min(),
            df_capabilities["Attack_Volatility_Short"].max(),
        )
        v_def_min, v_def_max = (
            df_capabilities["Defense_Volatility_Short"].min(),
            df_capabilities["Defense_Volatility_Short"].max(),
        )

        # 2. HELPER FUNCTION TO MAP EACH TEAM TO THE UNIFIED 0-100 PROFILE
        def calculate_pentagon_vectors(stats):
            # A. Base Elo (Higher is better)
            r_elo = ((stats["Elo_Rating"] - elo_min) / (elo_max - elo_min)) * 100

            # B. Poisson Attack (Higher is better)
            r_atk = ((stats["Poisson_Attack"] - atk_min) / (atk_max - atk_min)) * 100

            # C. Poisson Defense (Lower is better -> Invert)
            r_def = ((def_max - stats["Poisson_Defense"]) / (def_max - def_min)) * 100

            # D. Elo Momentum (Signed Min-Max -> 0 anchors near 50)
            r_mom = ((stats["Elo_Momentum"] - mom_min) / (mom_max - mom_min)) * 100

            # E. Combined Squad Consistency Index (Invert both CVs, then average)
            c_atk = (
                (v_atk_max - stats["Attack_Volatility_Short"])
                / (v_atk_max - v_atk_min)
                * 100
            )
            c_def = (
                (v_def_max - stats["Defense_Volatility_Short"])
                / (v_def_max - v_def_min)
                * 100
            )
            r_stbl = (c_atk + c_def) / 2.0

            return [r_atk, r_def, r_elo, r_mom, r_stbl]

        # Generate scaled radius vectors
        norm_a = calculate_pentagon_vectors(stats_a)
        norm_b = calculate_pentagon_vectors(stats_b)

        # 3. DEFINE PENTAGON LABELS & EXTRACT RAW VALUES FOR HOVER OVERLAYS
        labels = [
            "Attack Power",
            "Defense Solidity",
            "Elo Rating",
            "Form Momentum",
            "Squad Stability",
        ]

        # Create human-readable raw string representations for tooltips
        raw_text_a = [
            f"{stats_a['Poisson_Attack']:.2f} xG",
            f"{stats_a['Poisson_Defense']:.2f} xG (Conceded)",
            f"{int(stats_a['Elo_Rating'])} pts",
            f"{'+' if stats_a['Elo_Momentum'] > 0 else ''}{stats_a['Elo_Momentum']:.1f} Δ",
            f"Atk CV: {stats_a['Attack_Volatility_Short']:.2f} | Def CV: {stats_a['Defense_Volatility_Short']:.2f}",
        ]

        raw_text_b = [
            f"{stats_b['Poisson_Attack']:.2f} xG",
            f"{stats_b['Poisson_Defense']:.2f} xG (Conceded)",
            f"{int(stats_b['Elo_Rating'])} pts",
            f"{'+' if stats_b['Elo_Momentum'] > 0 else ''}{stats_b['Elo_Momentum']:.1f} Δ",
            f"Atk CV: {stats_b['Attack_Volatility_Short']:.2f} | Def CV: {stats_b['Defense_Volatility_Short']:.2f}",
        ]

        # 4. CLOSE THE GEOMETRIC LOOPS FOR PERFECT PENTAGON AREA RENDERING
        labels_closed = labels + [labels[0]]
        norm_a_closed = norm_a + [norm_a[0]]
        norm_b_closed = norm_b + [norm_b[0]]
        raw_a_closed = raw_text_a + [raw_text_a[0]]
        raw_b_closed = raw_text_b + [raw_text_b[0]]

        # Trace Profile: Team A
        fig_sandbox.add_trace(
            go.Scatterpolar(
                r=norm_a_closed,
                theta=labels_closed,
                fill="toself",
                name=team_a,
                marker=dict(color=DARK_THEME["accent"]),
                text=raw_a_closed,
                hovertemplate=f"<b>{team_a}</b><br>%{{theta}}: <b>%{{text}}</b><extra></extra>",
            )
        )

        # Trace Profile: Team B
        fig_sandbox.add_trace(
            go.Scatterpolar(
                r=norm_b_closed,
                theta=labels_closed,
                fill="toself",
                name=team_b,
                marker=dict(color="#e6739f"),
                text=raw_b_closed,
                hovertemplate=f"<b>{team_b}</b><br>%{{theta}}: <b>%{{text}}</b><extra></extra>",
            )
        )

        fig_sandbox.update_layout(
            title="<b>🔥 TEAM CAPABILITIES</b>",
            polar=dict(
                radialaxis=dict(
                    visible=True,
                    range=[0, 105],
                    showticklabels=False,
                    gridcolor="#2d2d2d",
                ),
                angularaxis=dict(
                    gridcolor="#2d2d2d",
                    linecolor="#2d2d2d",
                    ticks="",
                ),
                bgcolor=DARK_THEME["paper"],
            ),
            legend=dict(
                orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1
            ),
        )

        sandbox_output = apply_mission_control_layout(fig_sandbox)

    sandbox_output
    return


@app.cell
def _(
    DARK_THEME,
    df_capabilities,
    df_forecast,
    has_stochastic,
    mo,
    view_mode_toggle,
):
    _is_stoch_mode = "Stochastic" in view_mode_toggle.value

    # 1. Establish structural constants
    ALL_POSSIBLE_STAGES = {
        "R32 %": ("R32 %", "Round of 32", "#4a47a3"),
        "R16 %": ("R16 %", "Round of 16", "#ff7b54"),
        "QF %": ("QF %", "Quarter-Finals", "#1f4068"),
        "SF %": ("SF %", "Semi-Finals", "#16c79a"),
        "Final %": ("Final %", "Finalist", "#e6739f"),
        "Champion %": ("Champion %", "Champion", "#00adb5"),
    }

    available_column_stages = {}
    default_stages = []

    # 2. Flexible schema parser to adapt to structural refactors
    if has_stochastic and df_forecast is not None:
        for k, v in ALL_POSSIBLE_STAGES.items():
            clean_k = k.replace(" %", "").strip()

            matched_col = None
            if k in df_forecast.columns:
                matched_col = k
            elif clean_k in df_forecast.columns:
                matched_col = clean_k
            elif v[1] in df_forecast.columns:
                matched_col = v[1]

            if matched_col:
                available_column_stages[v[1]] = matched_col
                if k in ["QF %", "SF %", "Final %", "Champion %"]:
                    default_stages.append(v[1])

        max_teams = len(df_capabilities)
    else:
        available_column_stages = {"No Stochastic Data Available": ""}
        default_stages = []
        max_teams = 10

    # 3. Re-instantiate widgets with updated safe values
    stage_selector = mo.ui.multiselect(
        options=available_column_stages,
        value=default_stages,
        label="🏆 TOURNAMENT PROGRESSION",
    )

    team_count_slider = mo.ui.slider(
        start=4, stop=max_teams, step=1, value=min(8, max_teams), label="🏃 SQUAD DEPTH"
    )

    if has_stochastic and df_forecast is not None and _is_stoch_mode:
        stochastic_controls = mo.md(
            f"""
            <div style="display: flex; gap: 30px; margin: 15px 0;">
                <div style="flex: 2; background: {DARK_THEME["paper"]}; padding: 14px; border-radius: 6px; border: 1px solid #333;">{stage_selector}</div>
                <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 14px; border-radius: 6px; border: 1px solid #333;">{team_count_slider}</div>
            </div>
            """
        )
    else:
        stochastic_controls = mo.md("")

    stochastic_controls
    return ALL_POSSIBLE_STAGES, stage_selector, team_count_slider


@app.cell
def _(
    ALL_POSSIBLE_STAGES,
    apply_mission_control_layout,
    df_forecast,
    go,
    has_stochastic,
    mo,
    stage_selector,
    team_count_slider,
    view_mode_toggle,
):
    _is_stoch_mode = "Stochastic" in view_mode_toggle.value

    if not has_stochastic or df_forecast is None:
        stochastic_visual = mo.md(
            """
            ### 🎲 STOCHASTIC PROBABILITY ANALYSIS
            > 🔴 Monte Carlo suite disabled for active simulation run.
            >
            > ➡️ `RUN_MONTE_CARLO = True` to populate this predictive node.
            """
        )
    elif not _is_stoch_mode:
        # Collapse into thin air when user chooses deterministic view tracking
        stochastic_visual = mo.md("")
    else:
        # 1. Read reactive parameters from the control cell
        selected_stage_keys = stage_selector.value
        num_display_teams = team_count_slider.value

        if not selected_stage_keys:
            stochastic_visual = mo.md(
                "> ⚠️ **Visualization Alert:** Please select at least one tournament progression layer to render the chart analysis."
            )
        else:
            # 2. Extract and sort contender profiles dynamically based on baseline Championship power
            top_contenders = (
                df_forecast.sort_values(by="Champion %", ascending=False)
                .head(num_display_teams)
                .copy()
            )

            # 3. Compute dynamic scaling boundaries directly using the selected keys
            highest_visible_prob = top_contenders[selected_stage_keys].max().max()
            x_max_bound = min(100.0, float(highest_visible_prob) * 1.05)
            if x_max_bound <= 0:
                x_max_bound = 100.0

            # 4. Construct the visualization chart
            fig_survival = go.Figure()

            for _stoch_key in selected_stage_keys:
                if _stoch_key in ALL_POSSIBLE_STAGES:
                    _col_info = ALL_POSSIBLE_STAGES[_stoch_key]

                    fig_survival.add_trace(
                        go.Bar(
                            y=top_contenders["Country"],
                            x=top_contenders[_stoch_key],
                            name=_col_info[1],
                            orientation="h",
                            marker=dict(color=_col_info[2]),
                            hovertemplate="%{y} "
                            + _col_info[1]
                            + ": <b>%{x:.2f}%</b><extra></extra>",
                        )
                    )

            fig_survival.update_layout(
                title="<b>🎲 TOURNAMENT PROGRESSION</b>",
                barmode="group",
                xaxis=dict(
                    title="Probability / %", gridcolor="#222222", range=[0, x_max_bound]
                ),
                yaxis=dict(title="", autorange="reversed"),
                legend=dict(
                    orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1
                ),
            )

            stochastic_visual = apply_mission_control_layout(fig_survival)

    stochastic_visual
    return


@app.cell
def _(df_tables, mo):
    # Identify all active groups parsed by the backend
    available_groups = sorted(df_tables["group"].unique())

    # Spawn a reactive dropdown selector component
    group_dropdown = mo.ui.dropdown(
        options=available_groups, value=available_groups[0], label="GROUP"
    )
    return (group_dropdown,)


@app.cell
def _(
    DARK_THEME,
    df_matchups,
    df_tables,
    df_tournament,
    df_xtables,
    group_dropdown,
    mo,
    pd,
    view_mode_toggle,
):
    _is_stoch_mode = "Stochastic" in view_mode_toggle.value

    # 1. Extract the reactive value from the dropdown cell
    selected_group = group_dropdown.value
    group_filtered_df = df_tables[df_tables["group"] == selected_group].copy()

    # 2. Render either the Deterministic Table or Expected Stochastic Table (xTables)
    if _is_stoch_mode and df_xtables is not None:
        # Map out exactly the teams in this group
        grp_teams = group_filtered_df["team"].tolist()
        group_display_df = df_xtables[df_xtables["team"].isin(grp_teams)].copy()

        group_display_df = group_display_df.rename(
            columns={
                "team": "Country",
                "expected_points": "xPts",
                "expected_gd": "xGD",
                "group_winner_probability_pct": "1st %",
                "group_runner_up_probability_pct": "2nd %",
                "wildcard_probability_pct": "Wildcard %",
                "total_qualification_pct": "Qual %",
            }
        )[["Country", "xPts", "xGD", "1st %", "2nd %", "Wildcard %", "Qual %"]]

        group_display_df = group_display_df.sort_values(
            by="xPts", ascending=False
        ).reset_index(drop=True)
        group_display_df.index += 1
        group_display_df.index.name = "Pos"
        group_display_df = group_display_df.reset_index()
    else:
        group_display_df = (
            group_filtered_df[
                [
                    "position",
                    "team",
                    "points",
                    "goals_for",
                    "goals_against",
                    "goals_diff",
                ]
            ]
            .rename(
                columns={
                    "position": "Pos",
                    "team": "Country",
                    "points": "Pts",
                    "goals_for": "GF",
                    "goals_against": "GA",
                    "goals_diff": "GD",
                }
            )
            .sort_values(by="Pos")
            .reset_index(drop=True)
        )

    # 3. Isolate group fixtures for the active dropdown target
    group_label = f"Group {selected_group}"
    group_fixtures_df = df_tournament[df_tournament["round"] == group_label].copy()
    group_fixtures_df = group_fixtures_df.sort_values(by="match_id").reset_index(
        drop=True
    )
    group_fixtures_df["matchday"] = (group_fixtures_df.index // 2) + 1

    # 4. Loop through the 3 matchdays and pre-render the visual templates
    group_tabs_content = {}

    for grp_day in [1, 2, 3]:
        day_matches = group_fixtures_df[group_fixtures_df["matchday"] == grp_day]
        day_cards_html = []

        for _, grp_match in day_matches.iterrows():
            grp_home_team = grp_match["home_team"]
            grp_away_team = grp_match["away_team"]
            grp_venue_tag = (
                f"📍 {grp_match['venue']}" if pd.notna(grp_match.get("venue")) else ""
            )

            if _is_stoch_mode and df_matchups is not None:
                _actual_venue = grp_match.get("venue_country", "Neutral")
                if grp_home_team != _actual_venue and grp_away_team != _actual_venue:
                    _lookup_venue = "Neutral"
                else:
                    _lookup_venue = (
                        _actual_venue
                        if _actual_venue in ["United States", "Mexico", "Canada"]
                        else "Neutral"
                    )

                _matchup_row = df_matchups[
                    (df_matchups["home_team"] == grp_home_team)
                    & (df_matchups["away_team"] == grp_away_team)
                    & (df_matchups["venue_country"] == _lookup_venue)
                ]

                if not _matchup_row.empty:
                    _m_data = _matchup_row.iloc[0]
                    h_pct = float(_m_data["grp_win_home"])
                    d_pct = float(_m_data["grp_draw"])
                    a_pct = float(_m_data["grp_win_away"])

                    _match_resolution_html = f"""
                    <div style="display: flex; flex-direction: column; gap: 8px; padding: 4px 0;">
                        <div style="display: flex; justify-content: space-between; font-weight: bold; font-size: 15px;">
                            <span style="color: {DARK_THEME["accent"]};">{grp_home_team}</span>
                            <span style="color: #666; font-size: 11px;">vs</span>
                            <span style="color: #e6739f;">{grp_away_team}</span>
                        </div>
                        <div style="display: flex; height: 8px; border-radius: 4px; overflow: hidden; background: #262626;">
                            <div style="width: {h_pct}%; background: {DARK_THEME["accent"]};"></div>
                            <div style="width: {d_pct}%; background: {DARK_THEME["muted"]};"></div>
                            <div style="width: {a_pct}%; background: #e6739f;"></div>
                        </div>
                        <div style="display: flex; justify-content: space-between; font-size: 10px; color: #ccc;">
                            <span>{h_pct:.1f}%</span>
                            <span style="color: #888;">DRAW {d_pct:.1f}%</span>
                            <span>{a_pct:.1f}%</span>
                        </div>
                    </div>
                    """
                else:
                    _match_resolution_html = "<div>Matchup Artifact Missing</div>"

                # Clear out the proxy footer for Stochastic lookups
                _proxy_footer_html = ""
            else:
                grp_h_goals = int(grp_match["predicted_home_goals"])
                grp_a_goals = int(grp_match["predicted_away_goals"])
                grp_winner = grp_match["winner_name_meta"]
                grp_is_draw = str(grp_winner).lower() in [
                    "draw",
                    "none",
                    "nan",
                    "draws",
                ]

                grp_home_bold = (
                    "bold"
                    if (grp_winner == grp_home_team and not grp_is_draw)
                    else "normal"
                )
                grp_home_color = (
                    "#fff" if (grp_winner == grp_home_team or grp_is_draw) else "#888"
                )
                grp_home_crown = (
                    "👑 " if (grp_winner == grp_home_team and not grp_is_draw) else ""
                )

                grp_away_bold = (
                    "bold"
                    if (grp_winner == grp_away_team and not grp_is_draw)
                    else "normal"
                )
                grp_away_color = (
                    "#fff" if (grp_winner == grp_away_team or grp_is_draw) else "#888"
                )
                grp_away_crown = (
                    "👑 " if (grp_winner == grp_away_team and not grp_is_draw) else ""
                )

                _match_resolution_html = f"""
                <div style="font-size: 16px; display: flex; justify-content: space-between; align-items: center; padding: 4px 0;">
                    <span style="font-weight: {grp_home_bold}; color: {grp_home_color};">{grp_home_crown}{grp_home_team}</span>
                    <span style="font-weight: bold; background: #262626; padding: 4px 10px; border-radius: 4px;">{grp_h_goals}</span>
                </div>
                <div style="font-size: 16px; display: flex; justify-content: space-between; align-items: center; padding: 4px 0; margin-bottom: 8px;">
                    <span style="font-weight: {grp_away_bold}; color: {grp_away_color};">{grp_away_crown}{grp_away_team}</span>
                    <span style="font-weight: bold; background: #262626; padding: 4px 10px; border-radius: 4px;">{grp_a_goals}</span>
                </div>
                """

                # Store the deterministic proxy values
                _proxy_footer_html = f"""
                <div style="border-top: 1px solid #2d2d2d; padding-top: 8px; font-size: 11px; display: flex; justify-content: space-between;">
                    <span>📐 Corners: {int(grp_match["corners"])}</span>
                    <span>🟨 Yellows: {int(grp_match["yellow_cards"])}</span>
                    <span>🟥 Reds: {int(grp_match["red_cards"])}</span>
                </div>
                """

            grp_card = f"""
            <div style="background-color: {DARK_THEME["paper"]}; border: 1px solid #333; border-radius: 6px; padding: 16px; margin: 10px 0px; font-family: monospace;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px; margin-bottom: 8px; display: flex; justify-content: space-between; align-items: center;">
                    <div style="display: flex; align-items: center;">
                        <span>🆔 {int(grp_match["match_id"])}</span>
                    </div>
                    <span>{grp_venue_tag}</span>
                </div>

                {_match_resolution_html}

                {_proxy_footer_html}
            </div>
            """
            day_cards_html.append(grp_card)

        group_tabs_content[f"ROUND {grp_day}"] = mo.Html("".join(day_cards_html))

    group_match_timeline = mo.ui.tabs(group_tabs_content)

    group_panel = mo.md(
        f"""
        🏟️ {group_dropdown}
        {mo.ui.table(group_display_df, pagination=False)}

        ### ⚽ GROUP {selected_group} MATCHES
        {group_match_timeline}
        """
    )

    group_panel
    return


@app.cell
def _(
    DARK_THEME,
    df_matchups,
    df_tournament,
    df_tournament_stoch,
    mo,
    pd,
    view_mode_toggle,
):
    _is_stoch_mode = "Stochastic" in view_mode_toggle.value

    if _is_stoch_mode and df_tournament_stoch is not None:
        active_bracket_df = df_tournament_stoch
    else:
        active_bracket_df = df_tournament

    all_discovered_rounds = active_bracket_df["round"].dropna().unique()
    available_rounds = [
        r for r in all_discovered_rounds if not str(r).startswith("Group")
    ]

    def sort_key(round_name):
        r_lower = str(round_name).lower()
        if "32" in r_lower:
            return 1
        if "16" in r_lower:
            return 2
        if "quarter" in r_lower:
            return 3
        if "semi" in r_lower:
            return 4
        if "third" in r_lower or "3rd" in r_lower:
            return 5
        if "final" in r_lower:
            return 6
        return 7

    available_rounds = sorted(available_rounds, key=sort_key)
    tabs_content = {}

    for r in available_rounds:
        round_matches = active_bracket_df[active_bracket_df["round"] == r].copy()
        match_cards_html = []

        for _, match in round_matches.iterrows():
            _home_team = match["home_team"]
            _away_team = match["away_team"]
            venue_tag = f"📍 {match['venue']}" if pd.notna(match.get("venue")) else ""

            if _is_stoch_mode and df_matchups is not None:
                # Fetch actual venue, fallback to Neutral if not a host nation
                _actual_venue = match.get("venue_country", "Neutral")

                if _home_team != _actual_venue and _away_team != _actual_venue:
                    _lookup_venue = "Neutral"
                else:
                    _lookup_venue = (
                        _actual_venue
                        if _actual_venue in ["United States", "Mexico", "Canada"]
                        else "Neutral"
                    )

                _matchup_row = df_matchups[
                    (df_matchups["home_team"] == _home_team)
                    & (df_matchups["away_team"] == _away_team)
                    & (df_matchups["venue_country"] == _lookup_venue)
                ]

                if not _matchup_row.empty:
                    _m_data = _matchup_row.iloc[0]
                    h90 = float(_m_data["ko_win_90_home_pct"])
                    h120 = float(_m_data["ko_win_120_home_pct"])
                    hpen = float(_m_data["ko_win_pen_home_pct"])
                    a90 = float(_m_data["ko_win_90_away_pct"])
                    a120 = float(_m_data["ko_win_120_away_pct"])
                    apen = float(_m_data["ko_win_pen_away_pct"])

                    h_tot = h90 + h120 + hpen
                    a_tot = a90 + a120 + apen
                    w90, w120, wpen = h90 + a90, h120 + a120, hpen + apen

                    _match_resolution_html = f"""
                    <div style="display: flex; justify-content: space-between; font-weight: bold; font-size: 15px; padding-bottom: 12px; border-bottom: 1px solid #2d2d2d;">
                        <span style="color: {DARK_THEME["accent"]};">{_home_team} ({h_tot:.1f}%)</span>
                        <span style="color: #666; font-size: 12px;">vs</span>
                        <span style="color: #e6739f;">({a_tot:.1f}%) {_away_team}</span>
                    </div>

                    <div style="margin-top: 12px; margin-bottom: 6px;">
                        <div style="display: flex; justify-content: space-between; font-size: 9px; margin-bottom: 2px;">
                            <span style="color: {DARK_THEME["accent"]}">{h90:.1f}%</span>
                            <span style="color: #888; font-weight: bold;">90 MIN ({w90:.1f}%)</span>
                            <span style="color: #e6739f;">{a90:.1f}%</span>
                        </div>
                        <div style="display: flex; height: 5px; border-radius: 3px; overflow: hidden; background: #262626;">
                            <div style="width: {(h90 / w90 * 100) if w90 > 0 else 0}%; background: {DARK_THEME["accent"]};"></div>
                            <div style="width: {(a90 / w90 * 100) if w90 > 0 else 0}%; background: #e6739f;"></div>
                        </div>
                    </div>

                    <div style="margin-bottom: 6px;">
                        <div style="display: flex; justify-content: space-between; font-size: 9px; margin-bottom: 2px;">
                            <span style="color: {DARK_THEME["accent"]}">{h120:.1f}%</span>
                            <span style="color: #888; font-weight: bold;">⏱️ ET ({w120:.1f}%)</span>
                            <span style="color: #e6739f;">{a120:.1f}%</span>
                        </div>
                        <div style="display: flex; height: 5px; border-radius: 3px; overflow: hidden; background: #262626;">
                            <div style="width: {(h120 / w120 * 100) if w120 > 0 else 0}%; background: {DARK_THEME["accent"]};"></div>
                            <div style="width: {(a120 / w120 * 100) if w120 > 0 else 0}%; background: #e6739f;"></div>
                        </div>
                    </div>

                    <div style="margin-bottom: 8px;">
                        <div style="display: flex; justify-content: space-between; font-size: 9px; margin-bottom: 2px;">
                            <span style="color: {DARK_THEME["accent"]}">{hpen:.1f}%</span>
                            <span style="color: #888; font-weight: bold;">🥅 PENS ({wpen:.1f}%)</span>
                            <span style="color: #e6739f;">{apen:.1f}%</span>
                        </div>
                        <div style="display: flex; height: 5px; border-radius: 3px; overflow: hidden; background: #262626;">
                            <div style="width: {(hpen / wpen * 100) if wpen > 0 else 0}%; background: {DARK_THEME["accent"]};"></div>
                            <div style="width: {(apen / wpen * 100) if wpen > 0 else 0}%; background: #e6739f;"></div>
                        </div>
                    </div>
                    """
                else:
                    _match_resolution_html = "<div>Matchup Artifact Missing</div>"

                _et_badge = ""
                _pens_badge = ""

                # Clear out the proxy footer for Stochastic lookups
                _proxy_footer_html = ""

            else:
                _ko_winner = match["winner_name_meta"]
                h_goals = f"{pd.to_numeric(match['predicted_home_goals'], errors='coerce'):.0f}"
                a_goals = f"{pd.to_numeric(match['predicted_away_goals'], errors='coerce'):.0f}"

                m_corners = f"{pd.to_numeric(match['corners'], errors='coerce'):.0f}"
                m_yellows = (
                    f"{pd.to_numeric(match['yellow_cards'], errors='coerce'):.0f}"
                )
                m_reds = f"{pd.to_numeric(match['red_cards'], errors='coerce'):.0f}"

                went_to_et = match.get("extra_time", False)
                _has_et = (
                    went_to_et
                    if isinstance(went_to_et, bool)
                    else str(went_to_et).lower() in ["true", "1", "yes"]
                )

                went_to_pens = match.get("penalties", False)
                _has_pens = (
                    went_to_pens
                    if isinstance(went_to_pens, bool)
                    else str(went_to_pens).lower() in ["true", "1", "yes"]
                )

                home_bold = "bold" if _ko_winner == _home_team else "normal"
                home_color = "#fff" if _ko_winner == _home_team else "#888"
                home_crown = "👑 " if _ko_winner == _home_team else ""

                away_bold = "bold" if _ko_winner == _away_team else "normal"
                away_color = "#fff" if _ko_winner == _away_team else "#888"
                away_crown = "👑 " if _ko_winner == _away_team else ""

                _et_badge = ""
                _pens_badge = ""

                if _has_pens:
                    _pens_badge = '<span style="color: #e6739f; background: #2a1b24; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #4c283c; margin-left: 8px; letter-spacing: 0.5px; display: inline-block; vertical-align: middle;">🥅 PENS</span>'
                elif _has_et:
                    _et_badge = '<span style="color: #ff7b54; background: #2a1e1b; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #542e23; margin-left: 8px; letter-spacing: 0.5px; display: inline-block; vertical-align: middle;">⏱️ ET</span>'

                _match_resolution_html = f"""
                <div style="font-size: 16px; display: flex; justify-content: space-between; align-items: center; padding: 4px 0;">
                    <span style="font-weight: {home_bold}; color: {home_color};">{home_crown}{_home_team}</span>
                    <span style="font-weight: bold; background: #262626; padding: 4px 10px; border-radius: 4px;">{h_goals}</span>
                </div>
                <div style="font-size: 16px; display: flex; justify-content: space-between; align-items: center; padding: 4px 0; margin-bottom: 8px;">
                    <span style="font-weight: {away_bold}; color: {away_color};">{away_crown}{_away_team}</span>
                    <span style="font-weight: bold; background: #262626; padding: 4px 10px; border-radius: 4px;">{a_goals}</span>
                </div>
                """

                # Store the deterministic proxy values
                _proxy_footer_html = f"""
                <div style="border-top: 1px solid #2d2d2d; padding-top: 8px; font-size: 11px; display: flex; justify-content: space-between;">
                    <span>📐 Corners: {m_corners}</span>
                    <span>🟨 Yellows: {m_yellows}</span>
                    <span>🟥 Reds: {m_reds}</span>
                </div>
                """

            card = f"""
            <div style="background-color: {DARK_THEME["paper"]}; border: 1px solid #333; border-radius: 6px; padding: 16px; margin: 10px 0px; font-family: monospace;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px; margin-bottom: 8px; display: flex; justify-content: space-between; align-items: center;">
                    <div style="display: flex; align-items: center;">
                        <span>🆔 {int(match["match_id"])}</span>
                        {_et_badge}
                        {_pens_badge}
                    </div>
                    <span>{venue_tag}</span>
                </div>

                {_match_resolution_html}

                {_proxy_footer_html}
            </div>
            """
            match_cards_html.append(card)

        tabs_content[str(r).upper()] = mo.Html("".join(match_cards_html))

    knockout_tabs = mo.ui.tabs(tabs_content)

    knockout_panel = mo.md(
        f"""
        ---

        ### 💦 KNOCKOUT WATERFALL
        {knockout_tabs}
        """
    )

    knockout_panel
    return


@app.cell
def _(DARK_THEME, apply_mission_control_layout, df_tournament, go, mo, pd):
    stat_df = df_tournament.copy()
    stat_df["phase"] = (
        stat_df["round"]
        .str.startswith("Group", na=False)
        .map({True: "Group Stage", False: "Knockout Stage"})
    )

    t_matches = len(stat_df)
    t_goals = (
        stat_df["predicted_home_goals"].sum() + stat_df["predicted_away_goals"].sum()
    )
    t_corners = int(round(stat_df["corners"].sum()))
    t_yellows = int(round(stat_df["yellow_cards"].sum()))
    t_reds = int(round(stat_df["red_cards"].sum()))

    phase_metrics = []
    for phase_name in ["Group Stage", "Knockout Stage"]:
        phase_sub = stat_df[stat_df["phase"] == phase_name]
        m_count = len(phase_sub)

        if m_count > 0:
            tot_goals = (
                phase_sub["predicted_home_goals"].sum()
                + phase_sub["predicted_away_goals"].sum()
            )
            tot_corners = phase_sub["corners"].sum()
            tot_yellows = phase_sub["yellow_cards"].sum()
            tot_reds = phase_sub["red_cards"].sum()

            phase_metrics.append(
                {
                    "Phase": phase_name,
                    "Matches": m_count,
                    "Avg Goals": tot_goals / m_count,
                    "Avg Corners": tot_corners / m_count,
                    "Avg Yellows": tot_yellows / m_count,
                    "Avg Reds": tot_reds / m_count,
                    "Total Goals": tot_goals,
                    "Total Corners": tot_corners,
                    "Total Yellows": tot_yellows,
                    "Total Reds": tot_reds,
                }
            )

    phase_metrics.append(
        {
            "Phase": "Tournament",
            "Matches": t_matches,
            "Avg Goals": t_goals / t_matches if t_matches > 0 else 0,
            "Avg Corners": t_corners / t_matches if t_matches > 0 else 0,
            "Avg Yellows": t_yellows / t_matches if t_matches > 0 else 0,
            "Avg Reds": t_reds / t_matches if t_matches > 0 else 0,
            "Total Goals": t_goals,
            "Total Corners": t_corners,
            "Total Yellows": t_yellows,
            "Total Reds": t_reds,
        }
    )

    df_analytics = pd.DataFrame(phase_metrics)
    df_table_view = df_analytics.drop(
        columns=["Avg Reds", "Total Reds"], errors="ignore"
    )

    df_graph = df_analytics[df_analytics["Phase"] != "Tournament"].copy()

    fig_analytics = go.Figure()

    rate_columns = [
        ("Avg Goals", "Goals", "#00adb5"),
        ("Avg Corners", "Corners", "#34A853"),
        ("Avg Yellows", "Yellow Cards", "#f4b41a"),
    ]

    for col_key, col_label, col_color in rate_columns:
        fig_analytics.add_trace(
            go.Bar(
                x=df_graph["Phase"],
                y=df_graph[col_key],
                name=col_label,
                text=df_graph[col_key].round(2),
                textposition="auto",
                marker=dict(color=col_color),
                hovertemplate="%{x} " + col_label + ": <b>%{y:.2f}</b><extra></extra>",
            )
        )

    fig_analytics.update_layout(
        title="<b>📋 TOURNAMENT ANALYTICS</b>",
        barmode="group",
        xaxis=dict(title=""),
        yaxis=dict(title="Per Game Average Metric", gridcolor="#222222"),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    fig_analytics = apply_mission_control_layout(fig_analytics)

    kpi_banner = mo.Html(
        f"""
        <hr style="border-color: #2d2d2d; margin: 20px 0;">
        <div style="display: flex; gap: 15px; margin: 20px 0; text-align: center; font-family: monospace;">
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">MATCHES</div>
                <div style="font-size: 22px; font-weight: bold; color: #fff;">{t_matches}</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">GOALS</div>
                <div style="font-size: 22px; font-weight: bold; color: #00adb5;">{t_goals}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_goals / t_matches):.2f} / game</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">CORNERS</div>
                <div style="font-size: 22px; font-weight: bold; color: #34A853;">{t_corners}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_corners / t_matches):.2f} / game</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">YELLOW CARDS</div>
                <div style="font-size: 22px; font-weight: bold; color: #f4b41a;">{t_yellows}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_yellows / t_matches):.2f} / game</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">RED CARDS</div>
                <div style="font-size: 22px; font-weight: bold; color: #EA4335;">{t_reds}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_reds / t_matches):.2f} / game</div>
            </div>
        </div>
        """
    )

    analytics_table = mo.ui.table(df_table_view.round(3), pagination=False)

    dashboard_output = mo.vstack(
        [
            kpi_banner,
            fig_analytics,
            analytics_table,
        ]
    )

    dashboard_output
    return


@app.cell
def _(df_thirds, df_xtables, mo, view_mode_toggle):
    _is_stoch_mode = "Stochastic" in view_mode_toggle.value

    if _is_stoch_mode and df_xtables is not None:
        df_display = df_xtables[
            ["team", "wildcard_probability_pct", "total_qualification_pct"]
        ].copy()
        df_display = df_display.sort_values(
            by="wildcard_probability_pct", ascending=False
        ).reset_index(drop=True)
        df_display.index += 1
        df_display = df_display.reset_index().rename(
            columns={
                "index": "Rank",
                "team": "Country",
                "wildcard_probability_pct": "Wildcard %",
                "total_qualification_pct": "Qual %",
            }
        )
        df_display["Status"] = [
            "🟢 LIKELY" if i < 8 else "🔴 UNLIKELY" for i in range(len(df_display))
        ]
        heading = mo.md("### 🃏 3rd PLACE WILDCARDS")
        wildcard_table = mo.ui.table(df_display.head(15), pagination=False)
        third_places_panel = mo.vstack([heading, wildcard_table])

    elif df_thirds is None or df_thirds.empty:
        third_places_panel = mo.md("")
    else:
        df_display = df_thirds.copy().reset_index(drop=True)
        df_display = df_display.drop(columns=["position"], errors="ignore")
        df_display.index += 1
        df_display = df_display.reset_index().rename(columns={"index": "Rank"})
        df_display["Status"] = [
            "🟢 ADVANCING" if i < 8 else "❌ ELIMINATED" for i in range(len(df_display))
        ]

        df_display = df_display.rename(
            columns={
                "group": "Group",
                "team": "Country",
                "points": "Pts",
                "goals_against": "GA",
                "goals_for": "GF",
                "goals_diff": "GD",
            }
        )

        df_display["GD"] = df_display["GD"].apply(
            lambda x: f"+{int(x)}" if int(x) > 0 else str(int(x))
        )

        heading = mo.md("### 🃏 3rd PLACE WILDCARDS")
        wildcard_table = mo.ui.table(df_display, pagination=False)
        third_places_panel = mo.vstack([heading, wildcard_table])

    third_places_panel
    return


@app.cell
def _(df_forecast, has_stochastic, mo, pd, view_mode_toggle):
    _is_stoch_mode = "Stochastic" in view_mode_toggle.value

    # 1. Cleanly prepare the dataset profile or set an elegant fallback structure
    if has_stochastic and df_forecast is not None:
        display_forecast = df_forecast.copy()
        prob_cols = [c for c in display_forecast.columns if "%" in c]
        display_forecast[prob_cols] = display_forecast[prob_cols].round(2)
    else:
        # Safe empty fallback dataframe keeping schema structure intact
        display_forecast = pd.DataFrame(
            columns=[
                "Country",
                "R32 %",
                "R16 %",
                "QF %",
                "SF %",
                "Final %",
                "Champion %",
            ]
        )

    # 2. Always instantiate the interactive table component at the cell root
    forecast_table = mo.ui.table(
        data=display_forecast,
        pagination=True,
        page_size=10,
    )

    # 3. Conditionally build out the markdown visual frame for the UI
    if has_stochastic and df_forecast is not None and _is_stoch_mode:
        table_panel = mo.md(
            f"""
            ### 🔮 MULTIVERSE PROBABILITY LEDGER
            {forecast_table}
            """
        )
    else:
        table_panel = mo.md("")

    table_panel
    return


if __name__ == "__main__":
    app.run()
