# pyright: reportUnusedExpression=false
# ruff: noqa: B018

"""🏆 FIFA World Cup 2026 Prediction & Simulation Dashboard.

This module orchestrates a reactive front-end dashboard built natively in Marimo,
designed to ingest, evaluate, and visualize predictive outputs generated by the
underlying multi-model ensemble pipeline.

Execution Vectors:
    $ uv run marimo edit dashboard.py
    $ uv run marimo run dashboard.py

Dashboard Layout Matrix:
    1. 🚀 PARAMETER METRIC BANNER
       Displays real-time execution states, active pipeline configurations,
       and optimal consensus blend weights.

    2. 🎲 STOCHASTIC FRONTIER
       Knockout progression survival probabilities via Plotly.
       Multiverse probability ledger.

    4. 🏟️ DETERMINISTIC HORIZON
       Group Stage tables and matches.
       3rd Place Wildcards.
       Knockout Waterfall matches.
       Tournament Statistics.

    5. 🧪 MICRO HORIZON SANDBOX
       Head 2 head sandbox simulation match.
       Head 2 head capabilities comparisons.


Design Considerations:
    - This file explicitly silences 'unused-expression' warnings via file-level
      Pyright and Ruff directives to accommodate Marimo's terminal layout pattern.
    - Uses highly scoped responsive container components to guarantee dark-mode
      visual parity and strict monospaced numerical alignment.
"""

import marimo

__generated_with = "0.23.9"
app = marimo.App(width="medium", app_title="fifa-world-cup-2026-predictor")


@app.cell
def _():
    import glob
    import json
    import os

    import marimo as mo
    import pandas as pd
    import plotly.graph_objects as go

    # Define styling palette
    DARK_THEME = {
        "background": "#121212",
        "paper": "#1e1e1e",
        "text": "#e0e0e0",
        "accent": "#00adb5",
        "muted": "#6c757d",
    }

    # Apply global custom overrides to Plotly dark layout defaults
    def apply_mission_control_layout(fig):
        fig.update_layout(
            template="plotly_dark",
            paper_bgcolor=DARK_THEME["paper"],
            plot_bgcolor=DARK_THEME["background"],
            font=dict(color=DARK_THEME["text"], family="JetBrains Mono, monospace"),
            title=dict(
                font=dict(
                    family="'Inter', 'Segoe UI', system-ui, sans-serif",
                    size=16,
                    weight="bold",
                )
            ),
            margin=dict(l=40, r=40, t=50, b=40),
        )

        return fig

    return (
        DARK_THEME,
        apply_mission_control_layout,
        glob,
        go,
        json,
        mo,
        os,
        pd,
    )


@app.cell
def _(DARK_THEME, mo):
    # ⚡ GLOBAL CSS INJECTION LAYER
    global_styles = mo.Html(
        f"""
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');

            .marimo-output h1, h1 {{
                font-family: 'Inter', 'Segoe UI', system-ui, sans-serif !important;
                font-weight: 800 !important;
                letter-spacing: -1.5px !important;
                color: #ffffff !important;
            }}

            .marimo-output h2, h2 {{
                font-family: 'Inter', 'Segoe UI', system-ui, sans-serif !important;
                font-weight: 700 !important;
                letter-spacing: -1px !important;
                color: #ffffff !important;
                border-bottom: 1px solid #2d2d2d !important;
                padding-bottom: 8px !important;
            }}

            .marimo-output h3, h3, .marimo-output h4, h4 {{
                font-family: 'Inter', 'Segoe UI', system-ui, sans-serif !important;
                font-weight: 600 !important;
                letter-spacing: -0.5px !important;
                color: {DARK_THEME["accent"]} !important;
            }}

            .marimo-output p, p {{
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif !important;
                color: {DARK_THEME["text"]} !important;
                font-size: 14px !important;
                line-height: 1.6 !important;
            }}

            /* LAYER A: STANDARD MARKDOWN TABLES - CHANGED TO 100% MAX-WIDTH */
            .marimo-output table:not([class*="marimo"]) {{
                width: 100% !important;
                max-width: 100% !important;
                margin: 15px 0 !important;
                border-collapse: collapse !important;
            }}

            .marimo-output table:not([class*="marimo"]) th {{
                padding: 10px 16px !important;
                font-size: 13px !important;
                font-family: 'Inter', sans-serif !important;
                background-color: #1a1a1a !important;
                color: #ffffff !important;
                text-align: left !important;
                border-bottom: 2px solid #333 !important;
            }}

            .marimo-output table:not([class*="marimo"]) td {{
                padding: 10px 16px !important;
                font-size: 13px !important;
                font-family: -apple-system, BlinkMacSystemFont, sans-serif !important;
                color: {DARK_THEME["text"]} !important;
                border-bottom: 1px solid #262626 !important;
            }}

            .marimo-output table:not([class*="marimo"]) td code {{
                font-family: 'JetBrains Mono', monospace !important;
                font-size: 12px !important;
                background: #262626 !important;
                padding: 2px 6px !important;
                border-radius: 4px !important;
            }}

            /* LAYER B: GLOBAL HIGH-DENSITY INTERACTIVE DATA TABLES */
            marimo-table, [data-testid="ns-table"], div[class*="table-wrapper"] {{
                width: 100% !important;
                max-width: 100% !important;
            }}

            marimo-table th, [data-testid="ns-table"] th, div[class*="table"] th {{
                padding: 4px 6px !important;
                font-size: 11px !important;
                font-family: 'Inter', sans-serif !important;
                font-weight: 700 !important;
                background-color: #151515 !important;
                white-space: normal !important;
                word-break: break-word !important;
                line-height: 1.2 !important;
                vertical-align: bottom !important;
            }}

            marimo-table td, [data-testid="ns-table"] td, div[class*="table"] td {{
                padding: 4px 6px !important;
                font-size: 11px !important;
                font-family: 'JetBrains Mono', monospace !important;
                line-height: 1.2 !important;
            }}

            div[class*="table"] div, div[class*="grid"] div {{
                gap: 1px !important;
            }}
        </style>
        """
    )

    global_styles
    return


@app.cell
def _(glob, mo, os):
    # 1. Discover all execution folders by true chronological modification time
    all_runs = sorted(
        glob.glob(os.path.join("data", "runs", "run_*")), key=os.path.getmtime
    )
    if not all_runs:
        raise FileNotFoundError(
            "❌ Operational error: No simulation artifacts found in data/runs/."
        )

    # 2. Extract clean string folder names (basenames)
    run_names = [os.path.basename(r) for r in all_runs]

    # 3. Reverse the array order so the newest runs appear at the top of the dropdown list
    run_choices = list(reversed(run_names))

    # 4. Target the clean string name of the newest run as the default option
    latest_run_name = run_names[-1]

    # 5. Instantiate the dropdown using the foolproof string list strategy
    run_dropdown = mo.ui.dropdown(
        options=run_choices,
        value=latest_run_name,
        label="📂 SELECT SIMULATION RUN PROFILE",
    )

    run_selector_panel = mo.md(
        f"""
        <div style="background: #1a1a1a; padding: 14px; border-radius: 6px; border: 1px solid #00adb5; margin-bottom: 20px;">
            {run_dropdown}
        </div>
        """
    )

    run_selector_panel
    return (run_dropdown,)


@app.cell
def _(json, os, pd, run_dropdown):
    # 1. Get the clean folder name string from the dropdown selection state
    run_id = run_dropdown.value

    # 2. Explicitly reconstruct the accurate path relative to project root
    active_run_dir = os.path.join("data", "runs", run_id)

    # 3. Ingest selected run datasets into active dashboard scope
    df_tournament = pd.read_csv(
        os.path.join(active_run_dir, "predicted_tournament.csv")
    )
    df_tables = pd.read_csv(os.path.join(active_run_dir, "final_group_tables.csv"))
    df_thirds = pd.read_csv(os.path.join(active_run_dir, "third_places_standings.csv"))
    df_capabilities = pd.read_csv(
        os.path.join(active_run_dir, "pre_tournament_capabilities.csv")
    )

    # Defensive infrastructure fallback if auditing older run branches
    matchups_path = os.path.join(active_run_dir, "pre_computed_matchups.csv")
    if os.path.exists(matchups_path):
        df_matchups = pd.read_csv(matchups_path)
    else:
        df_matchups = pd.DataFrame(
            columns=[
                "home_team",
                "away_team",
                "is_neutral_venue",
                "ensemble_lambda_home",
                "ensemble_lambda_away",
            ]
        )

    # Safely unpack optional stochastic Monte Carlo matrix arrays
    forecast_path = os.path.join(active_run_dir, "monte_carlo_forecast.csv")
    has_stochastic = os.path.exists(forecast_path)
    df_forecast = pd.read_csv(forecast_path) if has_stochastic else None

    # 4. Parse running parameters from JSON configuration sheet
    with open(os.path.join(active_run_dir, "metadata.json"), "r") as f:
        metadata = json.load(f)

    config = metadata["config"]
    weights = metadata["ensemble_weights"]
    match_rules = metadata.get("match_rules", {"et_multiplier": 1.0/3.0, "fatigue_factor": 0.80})

    return (
        config,
        df_capabilities,
        df_forecast,
        df_matchups,
        df_tables,
        df_thirds,
        df_tournament,
        has_stochastic,
        run_id,
        weights,
        match_rules,
    )


@app.cell
def _(config, mo, run_id, weights):
    # 1. Resolve clean status strings ahead of time to keep the layout matrix readable
    nudge_status = "🟢 ACTIVE" if config["use_prior_nudge"] else "🔴 DISABLED"
    nudge_val = (
        f"📏 {config['nudge_strength']}" if config["use_prior_nudge"] else "❌ N/A"
    )

    mc_status = (
        f"🎲 {config['monte_carlo_runs']}"
        if config["run_monte_carlo"]
        else "🔴 DISABLED"
    )

    # 2. Render the streamlined technical metric banner
    header_panel = mo.md(
        f"""
        # 🚀 FIFA WORLD CUP 2026 PREDICTOR
        ### 📊 `{run_id}`
        | Parameter | Value | Ensemble Model | Weight |
        | :--- | :--- | :--- | :--- |
        | **Bayesian Prior Nudge** | {nudge_status} | 🧮 **Poisson MLE Baseline** | `{weights["poisson"]:.3f}` |
        | **Nudge Amplitude** | `{nudge_val}` | 📈 **Dynamic ELO Rating** | `{weights["elo"]:.3f}` |
        | **Monte Carlo Engine** | {mc_status} | 🌲 **XGBoost Count Regressor** | `{weights["xgb"]:.3f}` |
        """
    )

    header_panel
    return


@app.cell
def _(DARK_THEME, df_capabilities, df_forecast, has_stochastic, mo):
    # 1. Establish structural constants
    ALL_POSSIBLE_STAGES = {
        "R32 %": ("R32 %", "Round of 32", "#4a47a3"),
        "R16 %": ("R16 %", "Round of 16", "#ff7b54"),
        "QF %": ("QF %", "Quarter-Finals", "#1f4068"),
        "SF %": ("SF %", "Semi-Finals", "#16c79a"),
        "Final %": ("Final %", "Finalist", "#e6739f"),
        "Champion %": ("Champion %", "Champion", "#00adb5"),
    }

    # 2. Safely resolve widget options based on available dataframe columns
    if has_stochastic and df_forecast is not None:
        available_column_stages = {
            v[1]: k for k, v in ALL_POSSIBLE_STAGES.items() if k in df_forecast.columns
        }
        default_stages = [
            v[1]
            for k, v in ALL_POSSIBLE_STAGES.items()
            if k in ["QF %", "SF %", "Final %", "Champion %"]
            and k in df_forecast.columns
        ]
        max_teams = len(df_capabilities)
    else:
        available_column_stages = {"No Stochastic Data Available": ""}
        default_stages = []
        max_teams = 10

    # 3. Always instantiate the widgets at the cell root
    stage_selector = mo.ui.multiselect(
        options=available_column_stages,
        value=default_stages,
        label="🏆 TOURNAMENT PROGRESSION LAYERS",
    )

    team_count_slider = mo.ui.slider(
        start=4, stop=max_teams, step=1, value=min(8, max_teams), label="🏃 SQUAD DEPTH"
    )

    # 4. Conditionally build and display the visual matrix wrapper
    if has_stochastic and df_forecast is not None:
        stochastic_controls = mo.md(
            f"""
            ## 🎲 STOCHASTIC FRONTIER
            <div style="display: flex; gap: 30px; margin: 15px 0;">
                <div style="flex: 2; background: {DARK_THEME["paper"]}; padding: 14px; border-radius: 6px; border: 1px solid #333;">{stage_selector}</div>
                <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 14px; border-radius: 6px; border: 1px solid #333;">{team_count_slider}</div>
            </div>
            """
        )
    else:
        stochastic_controls = mo.md("")

    stochastic_controls
    return ALL_POSSIBLE_STAGES, stage_selector, team_count_slider


@app.cell
def _(
    ALL_POSSIBLE_STAGES,
    apply_mission_control_layout,
    df_forecast,
    go,
    has_stochastic,
    mo,
    stage_selector,
    team_count_slider,
):
    if not has_stochastic or df_forecast is None:
        stochastic_visual = mo.md(
            """
            ### 🎲 STOCHASTIC PROBABILITY ANALYSIS
            > 🔴 Monte Carlo suite disabled for active simulation run.
            >
            > ➡️ `RUN_MONTE_CARLO = True` to populate this predictive node.
            """
        )
    else:
        # 1. Read reactive parameters from the control cell
        selected_stage_keys = stage_selector.value
        num_display_teams = team_count_slider.value

        if not selected_stage_keys:
            stochastic_visual = mo.md(
                "> ⚠️ **Visualization Alert:** Please select at least one tournament progression layer to render the chart analysis."
            )
        else:
            # 2. Extract and sort contender profiles dynamically based on baseline Championship power
            top_contenders = (
                df_forecast.sort_values(by="Champion %", ascending=False)
                .head(num_display_teams)
                .copy()
            )

            # 3. Compute dynamic scaling boundaries directly using the selected keys
            highest_visible_prob = top_contenders[selected_stage_keys].max().max()
            x_max_bound = min(100.0, float(highest_visible_prob) * 1.05)
            if x_max_bound <= 0:
                x_max_bound = 100.0

            # 4. Construct the visualization chart
            fig_survival = go.Figure()

            # Using an underscore prefix makes this variable entirely private to this cell block
            for _stoch_key in selected_stage_keys:
                if _stoch_key in ALL_POSSIBLE_STAGES:
                    _col_info = ALL_POSSIBLE_STAGES[_stoch_key]

                    fig_survival.add_trace(
                        go.Bar(
                            y=top_contenders["Country"],
                            x=top_contenders[_stoch_key],
                            name=_col_info[1],
                            orientation="h",
                            marker=dict(color=_col_info[2]),
                            hovertemplate="%{y} "
                            + _col_info[1]
                            + ": <b>%{x:.2f}%</b><extra></extra>",
                        )
                    )

            fig_survival.update_layout(
                title="<b>KNOCKOUT PROGRESSION</b>",
                barmode="group",
                xaxis=dict(
                    title="Probability / %", gridcolor="#222222", range=[0, x_max_bound]
                ),
                yaxis=dict(title="", autorange="reversed"),
                legend=dict(
                    orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1
                ),
            )

            stochastic_visual = apply_mission_control_layout(fig_survival)

    stochastic_visual
    return


@app.cell
def _(df_forecast, has_stochastic, mo, pd):
    # 1. Cleanly prepare the dataset profile or set an elegant fallback structure
    if has_stochastic and df_forecast is not None:
        display_forecast = df_forecast.copy()
        prob_cols = [c for c in display_forecast.columns if "%" in c]
        display_forecast[prob_cols] = display_forecast[prob_cols].round(2)
    else:
        # Safe empty fallback dataframe keeping schema structure intact
        display_forecast = pd.DataFrame(
            columns=[
                "Country",
                "R32 %",
                "R16 %",
                "QF %",
                "SF %",
                "Final %",
                "Champion %",
            ]
        )

    # 2. Always instantiate the interactive table component at the cell root
    forecast_table = mo.ui.table(
        data=display_forecast,
        pagination=True,
        page_size=10,
    )

    # 3. Conditionally build out the markdown visual frame for the UI
    if has_stochastic and df_forecast is not None:
        table_panel = mo.md(
            f"""
            ### 🔮 MULTIVERSE PROBABILITY LEDGER
            {forecast_table}
            """
        )
    else:
        table_panel = mo.md("")

    table_panel
    return


@app.cell
def _(df_tables, mo):
    # Identify all active groups parsed by the backend
    available_groups = sorted(df_tables["group"].unique())

    # Spawn a reactive dropdown selector component
    group_dropdown = mo.ui.dropdown(
        options=available_groups, value=available_groups[0], label="GROUP"
    )
    return (group_dropdown,)


@app.cell
def _(DARK_THEME, df_tables, df_tournament, group_dropdown, mo, pd):
    # 1. Extract the reactive value from the dropdown cell
    selected_group = group_dropdown.value

    # 2. Filter down the data matrix
    group_filtered_df = df_tables[df_tables["group"] == selected_group].copy()

    # 3, Clean up the presentation column layout
    group_display_df = (
        group_filtered_df[
            ["position", "team", "points", "goals_for", "goals_against", "goals_diff"]
        ]
        .rename(
            columns={
                "position": "Pos",
                "team": "Country",
                "points": "Pts",
                "goals_for": "GF",
                "goals_against": "GA",
                "goals_diff": "GD",
            }
        )
        .sort_values(by="Pos")
        .reset_index(drop=True)
    )

    # 4.Isolate group fixtures for the active dropdown target
    group_label = f"Group {selected_group}"
    group_fixtures_df = df_tournament[df_tournament["round"] == group_label].copy()

    # 5. Chronologically sort by match_id to establish the true round sequence
    group_fixtures_df = group_fixtures_df.sort_values(by="match_id").reset_index(
        drop=True
    )

    # 6. Compute dynamic Matchday indices (2 matches per team round)
    group_fixtures_df["matchday"] = (group_fixtures_df.index // 2) + 1

    # 7. Loop through the 3 matchdays and pre-render the visual templates
    group_tabs_content = {}

    for grp_day in [1, 2, 3]:
        day_matches = group_fixtures_df[group_fixtures_df["matchday"] == grp_day]
        day_cards_html = []

        for _, grp_match in day_matches.iterrows():
            grp_home_team = grp_match["home_team"]
            grp_away_team = grp_match["away_team"]
            grp_h_goals = int(grp_match["predicted_home_goals"])
            grp_a_goals = int(grp_match["predicted_away_goals"])
            grp_winner = grp_match["winner_name_meta"]

            # Symmetrical draw resolution handling with unique scoping
            grp_is_draw = str(grp_winner).lower() in ["draw", "none", "nan", "draws"]

            grp_home_bold = (
                "bold"
                if (grp_winner == grp_home_team and not grp_is_draw)
                else "normal"
            )
            grp_home_color = (
                "#fff" if (grp_winner == grp_home_team or grp_is_draw) else "#888"
            )
            grp_home_crown = (
                "👑 " if (grp_winner == grp_home_team and not grp_is_draw) else ""
            )

            grp_away_bold = (
                "bold"
                if (grp_winner == grp_away_team and not grp_is_draw)
                else "normal"
            )
            grp_away_color = (
                "#fff" if (grp_winner == grp_away_team or grp_is_draw) else "#888"
            )
            grp_away_crown = (
                "👑 " if (grp_winner == grp_away_team and not grp_is_draw) else ""
            )

            grp_venue_tag = (
                f"📍 {grp_match['venue']}" if pd.notna(grp_match.get("venue")) else ""
            )

            grp_card = f"""
            <div style="background-color: {DARK_THEME["paper"]}; border: 1px solid #333; border-radius: 6px; padding: 16px; margin: 10px 0px; font-family: monospace;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px; margin-bottom: 8px; display: flex; justify-content: space-between; align-items: center;">
                    <div style="display: flex; align-items: center;">
                        <span>🆔 {int(grp_match["match_id"])}</span>
                    </div>
                    <span>{grp_venue_tag}</span>
                </div>
                <div style="font-size: 16px; display: flex; justify-content: space-between; align-items: center; padding: 4px 0;">
                    <span style="font-weight: {grp_home_bold}; color: {grp_home_color};">
                        {grp_home_crown}{grp_home_team}
                    </span>
                    <span style="font-weight: bold; background: #262626; padding: 4px 10px; border-radius: 4px;">{grp_h_goals}</span>
                </div>
                <div style="font-size: 16px; display: flex; justify-content: space-between; align-items: center; padding: 4px 0; margin-bottom: 8px;">
                    <span style="font-weight: {grp_away_bold}; color: {grp_away_color};">
                        {grp_away_crown}{grp_away_team}
                    </span>
                    <span style="font-weight: bold; background: #262626; padding: 4px 10px; border-radius: 4px;">{grp_a_goals}</span>
                </div>
                <div style="border-top: 1px solid #2d2d2d; padding-top: 8px; font-size: 11px; color: {DARK_THEME["accent"]}; display: flex; justify-content: space-between;">
                    <span>📐 Corners: {int(grp_match["corners"])}</span>
                    <span>🟨 Yellows: {int(grp_match["yellow_cards"])}</span>
                    <span>🟥 Reds: {int(grp_match["red_cards"])}</span>
                </div>
            </div>
            """
            day_cards_html.append(grp_card)

        group_tabs_content[f"ROUND {grp_day}"] = mo.Html("".join(day_cards_html))

    # 8. Compile into a neat layout block
    group_match_timeline = mo.ui.tabs(group_tabs_content)

    group_panel = mo.md(
        f"""
        ## 🏟️ DETERMINISTIC HORIZON
        {group_dropdown}
        {mo.ui.table(group_display_df, pagination=False)}

        ### ⚽ GROUP {selected_group} MATCHES
        {group_match_timeline}
        """
    )

    group_panel
    return


@app.cell
def _(df_thirds, mo):
    # 1. Safeguard closure to handle initialization states safely
    if df_thirds is None or df_thirds.empty:
        third_places_panel = mo.md("")
    else:
        # 2. Re-index and build a clean display DataFrame matching your layout matrix
        df_display = df_thirds.copy().reset_index(drop=True)

        # Drop the redundant group position column before parsing the global rank
        df_display = df_display.drop(columns=["position"], errors="ignore")

        df_display.index = df_display.index + 1
        df_display = df_display.reset_index().rename(columns={"index": "Rank"})

        # Inject the semantic status badges directly into the data rows
        df_display["Status"] = [
            "🟢 ADVANCING" if i < 8 else "❌ ELIMINATED" for i in range(len(df_display))
        ]

        # Symmetrical column renaming to match your exact front-end headers
        df_display = df_display.rename(
            columns={
                "group": "Group",
                "team": "Country",
                "points": "Pts",
                "goals_against": "GA",
                "goals_for": "GF",
                "goals_diff": "GD",
            }
        )

        # Explicit sign formatting for Goal Difference (+ / -)
        df_display["GD"] = df_display["GD"].apply(
            lambda x: f"+{int(x)}" if int(x) > 0 else str(int(x))
        )

        # 3. Pivot to a native Marimo UI element to inherit dashboard width metrics
        heading = mo.md("### 🃏 3rd PLACE WILDCARDS")
        wildcard_table = mo.ui.table(df_display, pagination=False)

        # 4. Stack elements using the exact layout pattern from your Analytics Hub
        third_places_panel = mo.vstack([heading, wildcard_table])

    third_places_panel
    return


@app.cell
def _(DARK_THEME, df_tournament, mo, pd):
    # Initiate safe defaults with underscores to keep them strictly local
    _home_team = ""
    _away_team = ""
    _ko_winner = ""

    # 1. Dynamically capture all unique rounds that are NOT group stage matches
    all_discovered_rounds = df_tournament["round"].dropna().unique()
    available_rounds = [
        r for r in all_discovered_rounds if not str(r).startswith("Group")
    ]

    # 2. Sort key to keep the tabs tracking in chronological tournament order
    def sort_key(round_name):
        r_lower = str(round_name).lower()
        if "32" in r_lower:
            return 1
        if "16" in r_lower:
            return 2
        if "quarter" in r_lower:
            return 3
        if "semi" in r_lower:
            return 4
        if "third" in r_lower or "3rd" in r_lower:
            return 5
        if "final" in r_lower:
            return 6
        return 7

    available_rounds = sorted(available_rounds, key=sort_key)

    # 3. Pre-render match card layouts for EACH tier into a master tabs dictionary
    tabs_content = {}

    for r in available_rounds:
        round_matches = df_tournament[df_tournament["round"] == r].copy()
        match_cards_html = []

        for _, match in round_matches.iterrows():
            _home_team = match["home_team"]
            _away_team = match["away_team"]
            _ko_winner = match["winner_name_meta"]
            h_goals = (
                f"{pd.to_numeric(match['predicted_home_goals'], errors='coerce'):.0f}"
            )
            a_goals = (
                f"{pd.to_numeric(match['predicted_away_goals'], errors='coerce'):.0f}"
            )
            m_corners = f"{pd.to_numeric(match['corners'], errors='coerce'):.0f}"
            m_yellows = f"{pd.to_numeric(match['yellow_cards'], errors='coerce'):.0f}"
            m_reds = f"{pd.to_numeric(match['red_cards'], errors='coerce'):.0f}"

            # Extra Time
            went_to_et = match.get("extra_time", False)
            _has_et = (
                went_to_et
                if isinstance(went_to_et, bool)
                else str(went_to_et).lower() in ["true", "1", "yes"]
            )

            # Penalty Shootout
            went_to_pens = match.get("penalties", False)
            _has_pens = (
                went_to_pens
                if isinstance(went_to_pens, bool)
                else str(went_to_pens).lower() in ["true", "1", "yes"]
            )

            home_bold = "bold" if _ko_winner == _home_team else "normal"
            home_color = "#fff" if _ko_winner == _home_team else "#888"
            home_crown = "👑 " if _ko_winner == _home_team else ""

            away_bold = "bold" if _ko_winner == _away_team else "normal"
            away_color = "#fff" if _ko_winner == _away_team else "#888"
            away_crown = "👑 " if _ko_winner == _away_team else ""

            _et_badge = ""
            _pens_badge = ""

            if _has_pens:
                _pens_badge = '<span style="color: #e6739f; background: #2a1b24; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #4c283c; margin-left: 8px; letter-spacing: 0.5px; display: inline-block; vertical-align: middle;">🥅 PENS</span>'
            elif _has_et:
                _et_badge = '<span style="color: #ff7b54; background: #2a1e1b; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #542e23; margin-left: 8px; letter-spacing: 0.5px; display: inline-block; vertical-align: middle;">⏱️ ET</span>'

            venue_tag = f"📍 {match['venue']}" if pd.notna(match.get("venue")) else ""

            card = f"""
            <div style="background-color: {DARK_THEME["paper"]}; border: 1px solid #333; border-radius: 6px; padding: 16px; margin: 10px 0px; font-family: monospace;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px; margin-bottom: 8px; display: flex; justify-content: space-between; align-items: center;">
                    <div style="display: flex; align-items: center;">
                        <span>🆔 {int(match["match_id"])}</span>
                        {_et_badge}
                        {_pens_badge}
                    </div>
                    <span>{venue_tag}</span>
                </div>
                <div style="font-size: 16px; display: flex; justify-content: space-between; align-items: center; padding: 4px 0;">
                    <span style="font-weight: {home_bold}; color: {home_color};">
                        {home_crown}{_home_team}
                    </span>
                    <span style="font-weight: bold; background: #262626; padding: 4px 10px; border-radius: 4px;">{h_goals}</span>
                </div>
                <div style="font-size: 16px; display: flex; justify-content: space-between; align-items: center; padding: 4px 0; margin-bottom: 8px;">
                    <span style="font-weight: {away_bold}; color: {away_color};">
                        {away_crown}{_away_team}
                    </span>
                    <span style="font-weight: bold; background: #262626; padding: 4px 10px; border-radius: 4px;">{a_goals}</span>
                </div>
                <div style="border-top: 1px solid #2d2d2d; padding-top: 8px; font-size: 11px; color: {DARK_THEME["accent"]}; display: flex; justify-content: space-between;">
                    <span>📐 Corners: {m_corners}</span>
                    <span>🟨 Yellows: {m_yellows}</span>
                    <span>🟥 Reds: {m_reds}</span>
                </div>
            </div>
            """
            match_cards_html.append(card)

        tabs_content[str(r).upper()] = mo.Html("".join(match_cards_html))

    knockout_tabs = mo.ui.tabs(tabs_content)

    knockout_panel = mo.md(
        f"""
        ---

        ### 💦 KNOCKOUT WATERFALL
        {knockout_tabs}
        """
    )

    knockout_panel
    return


@app.cell
def _(DARK_THEME, apply_mission_control_layout, df_tournament, go, mo, np, pd):
    stat_df = df_tournament.copy()
    stat_df["phase"] = (
        stat_df["round"]
        .str.startswith("Group", na=False)
        .map({True: "Group Stage", False: "Knockout Stage"})
    )

    t_matches = len(stat_df)
    t_goals = (
        stat_df["predicted_home_goals"].sum() + stat_df["predicted_away_goals"].sum()
    )
    t_corners = int(round(stat_df["corners"].sum()))
    t_yellows = int(round(stat_df["yellow_cards"].sum()))
    t_reds = int(round(stat_df["red_cards"].sum()))

    phase_metrics = []
    for phase_name in ["Group Stage", "Knockout Stage"]:
        phase_sub = stat_df[stat_df["phase"] == phase_name]
        m_count = len(phase_sub)

        if m_count > 0:
            tot_goals = (
                phase_sub["predicted_home_goals"].sum()
                + phase_sub["predicted_away_goals"].sum()
            )
            tot_corners = phase_sub["corners"].sum()
            tot_yellows = phase_sub["yellow_cards"].sum()
            tot_reds = phase_sub["red_cards"].sum()

            phase_metrics.append(
                {
                    "Phase": phase_name,
                    "Matches": m_count,
                    "Avg Goals": tot_goals / m_count,
                    "Avg Corners": tot_corners / m_count,
                    "Avg Yellows": tot_yellows / m_count,
                    "Avg Reds": tot_reds / m_count,
                    "Total Goals": tot_goals,
                    "Total Corners": tot_corners,
                    "Total Yellows": tot_yellows,
                    "Total Reds": tot_reds,
                }
            )

    phase_metrics.append(
        {
            "Phase": "Tournament",
            "Matches": t_matches,
            "Avg Goals": t_goals / t_matches if t_matches > 0 else 0,
            "Avg Corners": t_corners / t_matches if t_matches > 0 else 0,
            "Avg Yellows": t_yellows / t_matches if t_matches > 0 else 0,
            "Avg Reds": t_reds / t_matches if t_matches > 0 else 0,
            "Total Goals": t_goals,
            "Total Corners": t_corners,
            "Total Yellows": t_yellows,
            "Total Reds": t_reds,
        }
    )

    df_analytics = pd.DataFrame(phase_metrics)
    df_table_view = df_analytics.drop(
        columns=["Avg Reds", "Total Reds"], errors="ignore"
    )

    df_graph = df_analytics[df_analytics["Phase"] != "Tournament"].copy()

    fig_analytics = go.Figure()

    rate_columns = [
        ("Avg Goals", "Goals", "#00adb5"),
        ("Avg Corners", "Corners", "#1f4068"),
        ("Avg Yellows", "Yellow Cards", "#f4b41a"),
    ]

    for col_key, col_label, col_color in rate_columns:
        fig_analytics.add_trace(
            go.Bar(
                x=df_graph["Phase"],
                y=df_graph[col_key],
                name=col_label,
                text=df_graph[col_key].round(2),
                textposition="auto",
                marker=dict(color=col_color),
                hovertemplate="%{x} " + col_label + ": <b>%{y:.2f}</b><extra></extra>",
            )
        )

    fig_analytics.update_layout(
        title="<b>GROUP & KNOCKOUT METRICS</b>",
        barmode="group",
        xaxis=dict(title=""),
        yaxis=dict(title="Per Game Average Metric", gridcolor="#222222"),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    fig_analytics = apply_mission_control_layout(fig_analytics)

    kpi_banner = mo.Html(
        f"""
        <hr style="border-color: #2d2d2d; margin: 20px 0;">
        <h3>📈 TOURNAMENT ANALYTICS</h3>
        <div style="display: flex; gap: 15px; margin: 20px 0; text-align: center; font-family: monospace;">
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">TOTAL MATCHES</div>
                <div style="font-size: 22px; font-weight: bold; color: #fff;">{t_matches}</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">TOTAL GOALS</div>
                <div style="font-size: 22px; font-weight: bold; color: #00adb5;">{t_goals}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_goals / t_matches):.2f} / game</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">TOTAL CORNERS</div>
                <div style="font-size: 22px; font-weight: bold; color: #1f4068;">{t_corners}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_corners / t_matches):.2f} / game</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">YELLOW CARDS</div>
                <div style="font-size: 22px; font-weight: bold; color: #f4b41a;">{t_yellows}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_yellows / t_matches):.2f} / game</div>
            </div>
            <div style="flex: 1; background: {DARK_THEME["paper"]}; padding: 12px; border-radius: 6px; border: 1px solid #333;">
                <div style="color: {DARK_THEME["muted"]}; font-size: 11px;">RED CARDS</div>
                <div style="font-size: 22px; font-weight: bold; color: #e6739f;">{t_reds}</div>
                <div style="font-size: 10px; color: {DARK_THEME["muted"]};">{(t_reds / t_matches):.2f} / game</div>
            </div>
        </div>
        """
    )

    statistics_header = mo.md("#### 📋 STATISTICS")
    analytics_table = mo.ui.table(df_table_view.round(3), pagination=False)

    # 7. Stack everything together cleanly
    dashboard_output = mo.vstack(
        [
            kpi_banner,
            fig_analytics,
            statistics_header,
            analytics_table,
        ]
    )

    dashboard_output
    return


@app.cell
def _(DARK_THEME, df_capabilities, has_stochastic, mo):
    all_countries = sorted(df_capabilities["Country"].unique())

    team_a_ctrl = mo.ui.dropdown(
        options=all_countries, value=all_countries[0], label="🏷️ TEAM A"
    )
    team_b_ctrl = mo.ui.dropdown(
        options=all_countries,
        value=all_countries[1] if len(all_countries) > 1 else all_countries[0],
        label="🏷️ TEAM B",
    )
    is_ko_ctrl = mo.ui.checkbox(label="🏆 Knockout", value=False)

    is_stoch_ctrl = mo.ui.checkbox(
        label="🎲 Stochastic",
        value=False,
        disabled=not has_stochastic
    )

    headings = mo.md("""
    ---

    ## 🧪 MICRO HORIZON
    ### ⚔️ INTERACTIVE MATCHUP SANDBOX
    """)

    layout_text = f"""
    <div style="background: {DARK_THEME["paper"]}; padding: 20px; border-radius: 6px; border: 1px solid #333;">
        <div style="display: flex; gap: 20px; margin-bottom: 15px;">
            <div style="flex: 1;">{{team_a}}</div>
            <div style="flex: 1;">{{team_b}}</div>
        </div>
        <div style="display: flex; gap: 40px; justify-content: center; border-top: 1px solid #2d2d2d; padding-top: 15px;">
            {{is_ko}}
            {{is_stoch}}
        </div>
    </div>
    """

    sandbox_layout = mo.md(layout_text).batch(
        team_a=team_a_ctrl,
        team_b=team_b_ctrl,
        is_ko=is_ko_ctrl,
        is_stoch=is_stoch_ctrl
    )

    sandbox_form = sandbox_layout.form(
        bordered=False,
        submit_button_label="⚡ RUN SIMULATION",
        submit_button_tooltip="Execute neutral match!",
    )

    ui_panel = mo.vstack([headings, sandbox_form])
    ui_panel
    return (sandbox_form,)


@app.cell
def _(DARK_THEME, config, df_matchups, json, mo, sandbox_form, match_rules, has_stochastic):
    mo.stop(sandbox_form.value is None, mo.md(""))

    sim_data = sandbox_form.value
    sim_team_a = sim_data["team_a"]
    sim_team_b = sim_data["team_b"]
    is_ko = sim_data["is_ko"]
    is_stoch = sim_data.get("is_stoch", False) and has_stochastic

    mo.stop(
        sim_team_a == sim_team_b,
        mo.md("> ⚠️ **Simulation Error:** A team cannot play itself."),
    )

    host_country = "United States"
    if sim_team_a == "United States" or sim_team_b == "United States":
        host_country = "Mexico"

    match_row = df_matchups[
        (df_matchups["home_team"] == sim_team_a)
        & (df_matchups["away_team"] == sim_team_b)
        & (df_matchups["is_neutral_venue"] == host_country)
    ]

    if match_row.empty:
        mo.stop(
            True,
            mo.md("> ⚠️ **Data Missing:** Matchup not found in pre-computed artifact."),
        )

    # Extract Pre-Computed Static Values
    row_data = match_row.iloc[0]
    lambda_a = float(row_data["ensemble_lambda_home"])
    lambda_b = float(row_data["ensemble_lambda_away"])

    pred_a_goals = int(round(lambda_a))
    pred_b_goals = int(round(lambda_b))

    sim_winner = "Draw"
    if pred_a_goals > pred_b_goals:
        sim_winner = sim_team_a
    elif pred_b_goals > pred_a_goals:
        sim_winner = sim_team_b

    # UI Badges
    _et_badge = ""
    _pens_badge = ""

    if is_ko and sim_winner == "Draw":
        # Pull configurations dynamically from our active run profile
        et_multiplier = match_rules.get("et_multiplier", 1.0 / 3.0)
        fatigue_factor = match_rules.get("fatigue_factor", 0.80)

        # Project full continuous 120-minute timeline curves
        raw_a_120 = lambda_a * (1.0 + (et_multiplier * fatigue_factor))
        raw_b_120 = lambda_b * (1.0 + (et_multiplier * fatigue_factor))

        pred_a_goals = int(round(raw_a_120))
        pred_b_goals = int(round(raw_b_120))

        # 2. Re-evaluate if the tie was broken decisively during the extra 30 minutes
        if pred_a_goals > pred_b_goals:
            sim_winner = sim_team_a
            _et_badge = '<span style="color: #ff7b54; background: #2a1e1b; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #542e23; margin-left: 8px;">⏱️ ET</span>'
        elif pred_b_goals > pred_a_goals:
            sim_winner = sim_team_b
            _et_badge = '<span style="color: #ff7b54; background: #2a1e1b; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #542e23; margin-left: 8px;">⏱️ ET</span>'
        else:
            # 3. If still deadlocked at 120 mins, hand off to penalties
            sim_winner = sim_team_a if lambda_a >= lambda_b else sim_team_b
            _pens_badge = '<span style="color: #e6739f; background: #2a1b24; padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; border: 1px solid #4c283c; margin-left: 8px;">🥅 PENS</span>'

    # STOCHASTIC PROBABILITY ENGINE
    stoch_html = ""
    if is_stoch:
        if is_ko:
            wins_a = float(row_data["ko_win_home"])
            wins_b = float(row_data["ko_win_away"])
            draws = 0.0
        else:
            wins_a = float(row_data["grp_win_home"])
            wins_b = float(row_data["grp_win_away"])
            draws = float(row_data["grp_draw"])

        top_scores = json.loads(row_data["top_scorelines_json"])
        score_cards = []

        for rank_idx, score_data in enumerate(top_scores):
            score_line = score_data["score"]
            score_pct = float(score_data["pct"])
            score_cards.append(f"""
                <div style="flex: 1; background: #1a1a1a; padding: 10px; border-radius: 4px; border: 1px solid #2d2d2d; text-align: center;">
                    <div style="font-size: 10px; color: {DARK_THEME["muted"]}; margin-bottom: 2px; font-weight: bold;">RANK #{rank_idx + 1}</div>
                    <div style="font-size: 15px; font-weight: bold; color: #fff; margin-bottom: 4px; font-family: monospace;">{score_line}</div>
                    <div style="font-size: 11px; color: {DARK_THEME["accent"]}; font-weight: bold;">{score_pct:.1f}%</div>
                    <div style="background: #262626; height: 3px; border-radius: 2px; margin-top: 6px; overflow: hidden;">
                        <div style="background: {DARK_THEME["accent"]}; width: {score_pct * 3.5}%; height: 100%;"></div>
                    </div>
                </div>
            """)

        stoch_html = f"""
        <div style="border-top: 1px solid #2d2d2d; margin-top: 15px; padding-top: 12px;">
            <div style="font-size: 11px; color: {DARK_THEME["accent"]}; margin-bottom: 10px; font-weight: bold; letter-spacing: 0.5px;">🎲 PRE-COMPUTED MONTE CARLO DISTRIBUTION</div>
            <div style="display: flex; justify-content: space-between; font-size: 13px; color: #fff; margin-bottom: 14px; padding: 0 4px;">
                <span>{sim_team_a}: <b>{wins_a:.1f}%</b></span>
                <span>Draw: <b>{draws:.1f}%</b></span>
                <span>{sim_team_b}: <b>{wins_b:.1f}%</b></span>
            </div>
            <div style="font-size: 10px; color: {DARK_THEME["muted"]}; margin-bottom: 6px; font-weight: bold; letter-spacing: 0.25px;">⚽ TOP 3 SCORELINES (90 Min)</div>
            <div style="display: flex; gap: 10px;">
                {"".join(score_cards)}
            </div>
        </div>
        """

    card_html = f"""
    <div style="background-color: {DARK_THEME["paper"]}; border: 1px solid #00adb5; border-radius: 6px; padding: 16px; margin-top: 20px; font-family: monospace; max-width: 100%;">
        <div style="color: {DARK_THEME["accent"]}; font-size: 11px; margin-bottom: 8px; display: flex; justify-content: space-between; align-items: center; font-weight: bold;">
            <div style="display: flex; align-items: center;">
                <span>⚡ STATIC SIMULATION ARTIFACT</span>
                {_et_badge}
                {_pens_badge}
            </div>
            <span>📍 Neutral Turf</span>
        </div>
        <div style="font-size: 18px; display: flex; justify-content: space-between; align-items: center; padding: 6px 0;">
            <span style="font-weight: {"bold" if sim_winner == sim_team_a else "normal"}; color: {"#fff" if sim_winner == sim_team_a else "#888"};">
                {"👑 " if sim_winner == sim_team_a else ""}{sim_team_a}
            </span>
            <span style="font-weight: bold; background: #262626; padding: 4px 12px; border-radius: 4px;">{pred_a_goals}</span>
        </div>
        <div style="font-size: 18px; display: flex; justify-content: space-between; align-items: center; padding: 6px 0; margin-bottom: 8px;">
            <span style="font-weight: {"bold" if sim_winner == sim_team_b else "normal"}; color: {"#fff" if sim_winner == sim_team_b else "#888"};">
                {"👑 " if sim_winner == sim_team_b else ""}{sim_team_b}
            </span>
            <span style="font-weight: bold; background: #262626; padding: 4px 12px; border-radius: 4px;">{pred_b_goals}</span>
        </div>
        <div style="border-top: 1px solid #2d2d2d; padding-top: 10px; font-size: 12px; color: {DARK_THEME["muted"]}; display: flex; justify-content: space-between;">
            <span title="Expected Goals: {lambda_a:.2f} vs {lambda_b:.2f}">💡 xG: {lambda_a:.2f} - {lambda_b:.2f}</span>
            <span>⚖️ Win Margin: {abs(lambda_a - lambda_b):.2f}</span>
        </div>
        {stoch_html}
    </div>
    """

    simulation_output = mo.Html(card_html)
    simulation_output
    return


@app.cell
def _(
    DARK_THEME,
    apply_mission_control_layout,
    df_capabilities,
    go,
    mo,
    sandbox_form,
):

    mo.stop(
        sandbox_form.value is None,
        mo.md(""),
    )

    team_a = sandbox_form.value["team_a"]
    team_b = sandbox_form.value["team_b"]

    if team_a == team_b:
        sandbox_output = mo.md(
            "> ⚠️ **Configuration Alert:** Select two distinct country entities to run a comparative matchup profile."
        )
    else:
        stats_a = df_capabilities[df_capabilities["Country"] == team_a].iloc[0]
        stats_b = df_capabilities[df_capabilities["Country"] == team_b].iloc[0]

        fig_sandbox = go.Figure()

        metrics_to_compare = [
            ("Elo_Rating", "Elo Rating"),
            ("Poisson_Attack", "Poisson Attack"),
            ("Poisson_Defense", "Poisson Defense"),
            ("Poisson_Dominance", "Poisson Dominance"),
            ("Short_Term_Form_GF", "Form: Short-term"),
            ("Long_Term_Form_GF", "Form: Long-term"),
        ]

        labels = [m[1] for m in metrics_to_compare]
        vals_a = [float(stats_a[m[0]]) for m in metrics_to_compare]
        vals_b = [float(stats_b[m[0]]) for m in metrics_to_compare]

        max_values = {
            "Elo_Rating": 2100,
            "Poisson_Attack": 3.0,
            "Poisson_Defense": 3.0,
            "Poisson_Dominance": 4.0,
            "Short_Term_Form_GF": 3.0,
            "Long_Term_Form_GF": 3.0,
        }

        norm_a = [
            float(stats_a[m[0]]) / max_values[m[0]] * 100 for m in metrics_to_compare
        ]
        norm_b = [
            float(stats_b[m[0]]) / max_values[m[0]] * 100 for m in metrics_to_compare
        ]

        fig_sandbox.add_trace(
            go.Bar(
                y=labels,
                x=norm_a,
                name=team_a,
                orientation="h",
                text=[f"{v:.2f}" if v < 100 else f"{int(v)}" for v in vals_a],
                textposition="inside",
                marker=dict(color=DARK_THEME["accent"]),
                hovertemplate=f"<b>{team_a}</b><br>%{{y}}: %{{text}}<extra></extra>",
            )
        )

        fig_sandbox.add_trace(
            go.Bar(
                y=labels,
                x=norm_b,
                name=team_b,
                orientation="h",
                text=[f"{v:.2f}" if v < 100 else f"{int(v)}" for v in vals_b],
                textposition="inside",
                marker=dict(color="#e6739f"),
                hovertemplate=f"<b>{team_b}</b><br>%{{y}}: %{{text}}<extra></extra>",
            )
        )

        fig_sandbox.update_layout(
            title=f"{team_a.upper()} vs {team_b.upper()} - HEAD 2 HEAD CAPABILITIES",
            barmode="group",
            xaxis=dict(title="Relative Strength", showticklabels=False, range=[0, 110]),
            yaxis=dict(autorange="reversed"),
            legend=dict(
                orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1
            ),
        )

        sandbox_output = apply_mission_control_layout(fig_sandbox)

    sandbox_output
    return


if __name__ == "__main__":
    app.run()
